### ISSUE TITLE
kgtk ifnotexists return existing triple

### ISSUE THREAD

**Issue by JThanat** [usc-isi-i2/kgtk#100]
**Describe the bug**
Filter Not Exist does not return an expected behavior. In my case, the thing that exist in filter file still appear in the output. Please see the step to reproduce below. 

**To Reproduce**
1. Go to this [folder](https://drive.google.com/drive/folders/15rY9_vEh8q_GSPD-DWwKJmgTemlvtywf?usp=sharing) and download both `existing_triples.tsv` and `matched_triples_kgtk_format.tsv` 
2. Run the following command 
```
kgtk ifnotexists path/to/file/matched_triples_kgtk_format.tsv \
 --input-keys node1 label node2 \
 --filter-on path/to/file/exist_triples.tsv \
 --filter-keys node1 label node2 \
 > path/to/file/not_exist_triples.tsv
```

**Expected behavior**
3.  Read in data to check the result using any tools. In this example I use `pandas`
```
import pandas as pd

existing_candidate = pd.read_csv('path/to/file/exist_triples.tsv', delimiter='\t')
existing_candidate[(existing_candidate['node1'] == 'Q544059') & (existing_candidate['label'] == 'P1469')]
```
You should see this output:
![image](https://user-images.githubusercontent.com/10590807/88854152-bbdf3d00-d1a5-11ea-91e3-4b46734b9d30.png)

Try reading in the output of `kgtk ifnotexists` commands.
```
not_existing_candidate = pd.read_csv('path/to/file/not_exist_triples.tsv', delimiter='\t')
not_existing_candidate[(not_existing_candidate['node1'] == 'Q544059') & (not_existing_candidate['node2'] == '295149')]
```
![image](https://user-images.githubusercontent.com/10590807/88854357-0496f600-d1a6-11ea-93d2-8c52e14f4e11.png)

**Comment by saggu** [comment]
@JThanat The `folder` link goes to the `existing_triples.tsv` file. Please share the other file as well.

**Comment by JThanat** [comment]
@saggu  The link is updated

**Comment by saggu** [comment]
The triple in `exist_triples.tsv` is  `Q1938	P1469	"254141"` 

whereas the triple in `matched_triples_kgtk_format.tsv` is 

`Q1938	P1469	254141`

@CraigMiloRogers that seems to be one of the issues.


@JThanat what is your goal here? Filter out all triples for `Q1938` or just the specific triples present in the `exist_triples.tsv` file ?

**Comment by JThanat** [comment]
Thanks for the clarification. What I want to do is to filter out triples that **does not exist** in `exist_triples.tsv` (which I generate from filter `ifexist` from wikidata `edge.tsv` file. So,  I can take these non existing triples and put it in another KG that will be used to enrich Wikidata

**Comment by CraigMiloRogers** [comment]
The string quotes are significant, as @saggu points out.

**Comment by CraigMiloRogers** [comment]
Did you run the data through a spreadsheet, or some other program that may have stripped quotes?

**Comment by CraigMiloRogers** [comment]
`matched_triples_kgtk_format.tsv` also contains items such as `10.03.1981`, which are not valid KGTK.

**Comment by JThanat** [comment]
It's a soccer player data we get from (here)[https://github.com/minhptx/iswc-2016-semantic-labeling/blob/master/data/datasets/soccer/data/WM%202014%20Alle%20Spieler%20-%20players%20fifa.csv] to test our entity linking system. We have our entity linker that try to map raw data to Wikidata like `USC Wikifier`. And then after I link the data, I try to use KGTK to filter the output. So the quote stripping may come from either my processing module. I may need to check that again.

**Comment by saggu** [comment]
According to @JThanat the documentation on this command is not clear, he actually want to remove all triples from `matched_triples_kgtk_format.tsv` if `node1` exists in `existing_triples.tsv`.

So his filter keys should be `node1`

**Comment by JThanat** [comment]
I think one keyword that might help for easier understanding is `if all filter key are matched, the triple will be filtered `. When I reread the document again, this thing is actually just an interpretation from this table. 

![image](https://user-images.githubusercontent.com/10590807/89239447-144f7980-d5ae-11ea-9ce4-2da9514fa8c4.png)

I'm not sure what made me misunderstand it in the first place. But,  once I discussed with @saggu  everything in the table became clear to me.

**Comment by JThanat** [comment]
If I want all statements that does not exist in `existing_triples.tsv` then my command above should be correct right ? 
file1:
| node1 | label   | node2 | 
|-------|---------|-------|
| peter | zipcode | 12040 |
| peter | zipcode | 12345 |

existing triples in kg:
| node1 | label   | node2 | 
|-------|---------|-------|
| peter | zipcode | 12040 |

after `ifnotexists` 
result:
| node1 | label   | node2 | 
|-------|---------|-------|
| peter | zipcode | 12345 |

this way I can use `ifnotexists` result to enrich existing kg

**Comment by szeke** [comment]
@CraigMiloRogers please comment on this thread.

**Comment by CraigMiloRogers** [comment]
Yes, the `existing_triples.tsv` should be filtered as @JThanat described.

**Comment by CraigMiloRogers** [comment]
Closing this issue. The underlying problem was incocsistent formatting of user data.
