### ISSUE TITLE
Binder not working 

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#104]
kgtk fails to run because it wants graph tools

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/1074599/88968628-7170c580-d264-11ea-894b-37f368b43e44.png">

**Comment by dgarijo** [comment]
The second notebook I added will work because it starts a Docker image. 
This is covered in the documentation:

> The easiest way of running KGTK is through MyBinder. We have made available an example notebook to show some of the features of KGTK. The notebook may take 5-10 minutes to launch, please be patient. Note that in this notebook some KGTK commands (graph analytics and embeddings) will not run. To launch the notebook in your browser, click on the "Binder" icon: Binder
> 
> To see the graph analytics and embedding capabilities of KGTK, launch the following Notebook (launch usually requires 10-15 minutes): Binder

**Comment by dgarijo** [comment]
Just to follow up, I added clarifications in the documentation and readme (dev branch). They will be reflected when we do a new release.
