### ISSUE TITLE
Implode not working for coordinates

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/kgtk#105]
**Describe the bug**
Node2 of coordinate property `P625` is missing after implosion. 

**To Reproduce**
Run kgtk implode command:
```
unzip files.zip
kgtk implode exploded.tsv --remove-prefixed-columns True --without si_units language_suffix > imploded.tsv
```

[files.zip](https://github.com/usc-isi-i2/kgtk/files/5003594/files.zip)

**Expected behavior**
Node2 of `P625` should contain coordinate value

**Desktop (please complete the following information):**
KGTK 0.3.2

**Comment by CraigMiloRogers** [comment]
--verbose reveals: 
```
Imploding records from exploded.tsv
Input line 1: data type 'quantity': imploded value '2QUNIT-Qawsd-002' is not a valid quantity or number.
Input line 6: unrecognized data type 'coordinate'.
Input line 15: data type 'quantity': imploded value '0QUNIT-Qawsd-002' is not a valid quantity or number.
Input line 21: unrecognized data type 'coordinate'.
```

**Comment by CraigMiloRogers** [comment]
`coordinate` should be `location_coordinates`

**Comment by CraigMiloRogers** [comment]
```
kgtk implode --show-data-types
empty
list
number
quantity
string
language_qualified_string
location_coordinates
date_and_times
extension
boolean
symbol
```

**Comment by CraigMiloRogers** [comment]
Do you think there should be data type aliases (lqstring, coordinate, datetime) for easier use?

**Comment by CraigMiloRogers** [comment]
The `kgtk implode` command needs `--allow-lax-qnodes True` to process your qnodes. The KGTK default is to support only Qnodes as defined by Wikidata.

**Comment by CraigMiloRogers** [comment]
@kyao I've merged a new version of `kgtk implode` into the KGTK  `dev` repository. The new version is more agressive about pointing out the errors it encounters in the input file.  If you don't have access to this repository, we'll make a new release.
