### ISSUE TITLE
`import-wikidata` fails on early json dump of wikidata.

### ISSUE THREAD

**Issue by rongpenl** [usc-isi-i2/kgtk#108]
**Describe the bug**
`import-wikidata` fails on early json dump of wikidata.

**To Reproduce**
1. Go to https://archive.org/download/wikidata-json-20150330
2. Download the json dump.
3. Unzip it
4. Run `kgtk import-wikidata -i 20150330.json --node nodefile.tsv --edge edgefile.tsv --qual qualfile.tsv  --procs 1 --debug --lang en`

**Expected behavior**
Three kgtk files will be generated. The file size should be more than 1GB in general.

**Actual behavior**

An error was reported but program didn't stop. The generated kgtk files are about 100K. 

**Screenshots**
<img width="984" alt="Screen Shot 2020-08-03 at 10 54 01 AM" src="https://user-images.githubusercontent.com/45610532/89212047-a8521e80-d577-11ea-9c37-cc7944721ee1.png">

**Comment by CraigMiloRogers** [comment]
The "claims" section was missing.  Perhaps the early JSON dump had a different structure than current ones?

**Comment by CraigMiloRogers** [comment]
Due to the parallel processing implementation used by import-wikidata, it may be difficult to halt processing when the error is detected.

**Comment by rongpenl** [comment]
Thanks for the verification Craig. Per @filievski 's use case and Pedro's suggestion, we probably can focus on the post 2016 dumps for now.

**Comment by filievski** [comment]
For the record, the earliest dump that I tried so far (successfully) is from 20171227.

**Comment by CraigMiloRogers** [comment]
See also issue #173

**Comment by CraigMiloRogers** [comment]
`dumps/20170313.json.gz` generates
Process Process-4:
Traceback (most recent call last):
  File "/home/rogers/.local/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rogers/.local/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rogers/src/github/pyrallel/pyrallel/parallel_processor.py", line 419, in _run
    result = mapper.process(*args, **kwargs)
  File "/home/rogers/kgtk/github/kgtk3/kgtk/cli/import_wikidata.py", line 1167, in process
    typ = cp['mainsnak']['datatype']

**Comment by CraigMiloRogers** [comment]
`kgtk import-wikidata` has been changed to skip the records causing the problem.
