### ISSUE TITLE
Getting <class 'ValueError'> error when running the generate_wikidata_triples command

### ISSUE THREAD

**Issue by mtang724** [usc-isi-i2/kgtk#109]
**Describe the bug**
When I try to run the command *kgtk generate_wikidata_triples -pf wikibase_property_mapping_kgtk.tsv < kgtk_test.tsv > output_file.ttl*, I am getting the error 
*"UserWarning: Please raise KGTKException instead of <class 'ValueError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found"*

**To Reproduce**
1. input file: [kgtk_test.txt](https://github.com/usc-isi-i2/kgtk/files/5025249/kgtk_test.txt) (Cannot attach tsv format)
2. property file: 
[wikibase_property_mapping_kgtk.txt](https://github.com/usc-isi-i2/kgtk/files/5025251/wikibase_property_mapping_kgtk.txt)

3. kgtk generate_wikidata_triples -pf wikibase_property_mapping_kgtk.tsv < kgtk_test.tsv > output_file.ttl
UserWarning: Please raise KGTKException instead of <class 'ValueError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

**Expected behavior**
No error and generating the TTL file

**Screenshots**
![image](https://user-images.githubusercontent.com/12247351/89354456-e68a3380-d686-11ea-8768-b498fa14bfac.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
There is an inconsistency in the kgtk documentation, 
https://kgtk.readthedocs.io/en/latest/export/generate_wikidata_triples/
![image](https://user-images.githubusercontent.com/12247351/89354554-251fee00-d687-11ea-9810-c3a3402f0a22.png)
**property_type** here should be **data_type**

**Comment by rongpenl** [comment]
Thank you for feedback @mtang724. I will take a look later today.

**Comment by rongpenl** [comment]
@mtang724  I suppose you are using an old Mac that has `\r` as newline rather than `\n`.  The merge should solve your bug.

The inconsistency between `property_type` and `data_type` is due to the version of the doc which is based on the master branch I think. Can you take  look? @dgarijo Is it possible to have a dev branch based doc? Could open an issue. I am closing this one. Feel free to reopen it if the error persists.

**Comment by saggu** [comment]
@rongpenl Please keep this issue open until we have confirmation from @mtang724 that this is working

**Comment by mtang724** [comment]
Thank you @rongpenl and @saggu , I update the KGTK from the dev branch. Now I am getting a new issue
`UserWarning: Please raise KGTKException instead of <class 'OSError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found`

**Comment by saggu** [comment]
@rongpenl please explain what are the next steps? Is there a need to reinstall KGTK ?

**Comment by rongpenl** [comment]
@mtang724 Please reinstall KGTK and when you run your code, add `--debug` option. I am curious why the error is `OSError`. Is your file name correct?

**Comment by mtang724** [comment]
@rongpenl Hi, I reinstalled the KGTK from dev branch, I first uninstalled the KGTK then using "git pull && python setup.py install" command to install it again. Is this a correct process? The OSError is because "OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory."

**Comment by rongpenl** [comment]
Hi @mtang724 ，The `en_core_web_sm` is a model in spacy, which is required by kgtk. What you can do is the following.

1. Check that the version of your spacy library agrees with the specification in `requirements.txt`
2. Run `python -m spacy download en_core_web_sm` to donwload the model. You shouldn't need to link or provide a path somewhere, the default location is good.
3. Try the command again.

Let me know your result.

**Comment by mtang724** [comment]
Thanks @rongpenl , it works. But after that I still got the same value error issue. This time I add `--debug`, below is the Traceback:
`Traceback (most recent call last):
  File "/Users/mtang/miniconda/envs/new_kgtk-env/lib/python3.7/site-packages/kgtk/exceptions.py", line 42, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/mtang/miniconda/envs/new_kgtk-env/lib/python3.7/site-packages/kgtk/cli/generate_wikidata_triples.py", line 228, in run
    generator.entry_point(line_num+1,edge)
  File "/Users/mtang/miniconda/envs/new_kgtk-env/lib/python3.7/site-packages/kgtk/generator.py", line 448, in entry_point
    self.initialize_order_map(edge)
  File "/Users/mtang/miniconda/envs/new_kgtk-env/lib/python3.7/site-packages/kgtk/generator.py", line 69, in initialize_order_map
    id_index = edge_list.index("id")
ValueError: 'id' is not in list
/Users/mtang/miniconda/envs/new_kgtk-env/lib/python3.7/site-packages/kgtk/exceptions.py:60: UserWarning: Please raise KGTKException instead of <class 'ValueError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found`

**Comment by rongpenl** [comment]
Thanks @mtang724 , can you post a screeshot of your Mac OS version information? Which editor are you using? 

The issue is likely due to the fact that older Mac system use carriage return `\r` for new line.

**Comment by saggu** [comment]
@mtang724 @rongpenl I suggest you guys have a zoom meeting to help you better debug this issue

**Comment by rongpenl** [comment]
@mtang724 please send me an email on rli@isi.edu and let's schedule a meeting.

**Comment by mtang724** [comment]
@rongpenl My MacOS version is:
Catalina 10.15.4
![image](https://user-images.githubusercontent.com/12247351/89442783-65ca4680-d71d-11ea-93d6-6ce109fc391d.png)
@saggu yes, I am free to have a zoom call, I will schedule the call with @rongpenl

**Comment by mtang724** [comment]
Issue resolved by the new support of carriage return
