### ISSUE TITLE
Bug in Wikidata Import: Property datatype

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#130]
The Wikidata JSON file should have a datatype field for top-level property records. We aren't importing this field yet. We need this field for better analysis of Wikidata data, such as in the MAA project.

**Comment by CraigMiloRogers** [comment]
I'm testing a fix now.  There's a new column in the node output file, and an option new edge in the edge file.

**Comment by szeke** [comment]
Isn't this issue complete, ore redundant with the recent issue #183 ?

**Comment by CraigMiloRogers** [comment]
I want to cross-check the per-property value with the value in the claims edges. I'll open a new issue for this.
