### ISSUE TITLE
kgtk cat piped with head throws an error after finishing the task successfully

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#132]
```
(kgtk_env) amandeep@Amandeeps-MacBook-Pro MAA_Datasets % kgtk cat wikidata-20200803-all-edges.tsv.gz | head
id	node1	label	node2	rank
Q183-P2924-1	Q183	P2924	"2354371"	normal
Q183-P1333-1	Q183	P1333	@47.2700279/10.17844677	normal
Q183-P3221-1	Q183	P3221	"destination/germany"	normal
Q183-P227-1	Q183	P227	"4011882-4"	normal
Q183-P1792-1	Q183	P1792	Q3919754	normal
Q183-P2852-1	Q183	P2852	Q1061257	normal
Q183-P2852-2	Q183	P2852	Q25648823	normal
Q183-P2853-1	Q183	P2853	Q1123613	normal
Q183-P2853-2	Q183	P2853	Q1378312	normal
[Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
**To Reproduce**
1. Download `wikidata-20200803-all-edges.tsv.gz` file from  `https://drive.google.com/drive/u/1/folders/1QAtPByFuSXRN92_PE-aAZI2fMmlJQehA`
2. run command `kgtk cat wikidata-20200803-all-edges.tsv.gz | head`
3. The head rows are displayed along with the error at the end

I am running this from the `dev` branch

**Comment by CraigMiloRogers** [comment]
I expect that the problem happens because the "head" command closes the pipe from its source (`kgtk cat`), which then becomes disturbed that its output file has been closed.

**Comment by CraigMiloRogers** [comment]
The same thing happens if the input file is not ".gz"

**Comment by CraigMiloRogers** [comment]
I've changed the code in KgtkWriter to ignore pipe errors on normal output writes (but not when writing .gz files."
