### ISSUE TITLE
Exception in kgtk add-id

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#137]
**Describe the bug**
Run this command

kgtk add-id -i [sample_kgtk_edge_file_with_id.tsv](https://github.com/usc-isi-i2/kgtk/blob/dev/kgtk/tests/data/sample_kgtk_edge_file_with_id.tsv) --new-id-column-name id_new --old-id-column-name id

Throws this exception:

`local variable 'new_id_column_name' referenced before assignment`

**Expected behavior**
An output file with a new column `id_new`

**Comment by CraigMiloRogers** [comment]
A fix has been pushed into the dev branch.
