### ISSUE TITLE
Incorrect Exception in kgtk add-id ?

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#138]
**Describe the bug**
I specify an unknown `--id-style` option in `kgtk add-id`.
I expect to see `KGTKException` or `KGTKArgumentParseException`

Neither of these are thrown

**To Reproduce**
```
kgtk add-id -i <file_path> --id-style unknown
```

**Expected behavior**
I expect to see `KGTKException` or `KGTKArgumentParseException`

**Comment by CraigMiloRogers** [comment]
I see the following:

kgtk add-id -i kgtk/join/test/lift-file10.tsv --id-style unknown
usage: kgtk add-id [-h] [-i INPUT_FILE] [-o OUTPUT_FILE] [--old-id-column-name COLUMN_NAME] [--new-id-column-name COLUMN_NAME]
                   [--overwrite-id [optional true|false]] [--verify-id-unique [optional true|false]]
                   [--id-style {node1-label-node2,node1-label-num,node1-label-node2-num,node1-label-node2-id,empty,prefix###}] [--id-prefix PREFIX]
                   [--initial-id INTEGER] [--id-prefix-num-width INTEGER] [--id-concat-num-width INTEGER] [-v]
                   [INPUT_FILE]
kgtk add-id: error: argument --id-style: invalid choice: 'unknown' (choose from 'node1-label-node2', 'node1-label-num', 'node1-label-node2-num', 'node1-label-node2-id', 'empty', 'prefix###')
