### ISSUE TITLE
Change the names of output files to include a prefix

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#152]
In notebooks Example7 and Example8 we generate the Wikidata products. Enhance the scripts to include the ability to provide a PREFIX that gets prepended to all files so we can specify the Wikidata date:

PREFIX = WD.20200928

Files will look like this for the Wikidata outputs 
`WD. 20200928.part.external_id.tsv.gz`

and like this for the subset outputs
`WD. 20200928.Q7187.part.external_id.tsv.gz`

**Comment by saggu** [comment]
so we are not doing this? Keeping the versions in different folders as we discussed in Today's KGTK meeting ? @szeke

**Comment by szeke** [comment]
Let's keep the different versions in different folders, the file names do not change.

**Comment by saggu** [comment]
Closing this issue, using date based folder names for version control
