### ISSUE TITLE
Unit Test Error for text_embedding

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#153]
cd kgtk/tests && python3 -m unittest discover --verbose
Traceback (most recent call last):
  File "/home/rogers/elicit/github/kgtk/kgtk/cli/text_embedding.py", line 143, in main
    input_file = open(filename, "r") if str(filename) != "-" else sys.stdin
FileNotFoundError: [Errno 2] No such file or directory: '/Users/amandeep/Github/maa-analysis/MAA_Datasets/v3.2.0/10000.tsv'

**Comment by saggu** [comment]
oops, this is not ready for unit tests, I have commented out the code for now
