### ISSUE TITLE
Stable IDs for Wikidata Import

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#155]
Generate stable IDs during Wikidata import.  The ID value should change only when the the data changes.

**Comment by CraigMiloRogers** [comment]
Problem: aliases are sequenced.

Discussion: Including the alias value in the ID might be too large and might contain problematic characters.

Solution: Include a hash of the alias value in the ID.  Retain a sequence number in case of hash collisions.

**Comment by CraigMiloRogers** [comment]
Problem: properties are sequenced.

Discussion: The code allows for multiple instances of a property.  Need to sort by property, hash the value, and add a sequence number in case of collisions (or multiple entries due to different qualifiers).

**Comment by CraigMiloRogers** [comment]
Problem: qualifiers are sequenced.

Discussion: order the qualifiers by qualifier property.  Add a hash for the qualifier value.  Add a sequence number in case of collisions.

**Comment by CraigMiloRogers** [comment]
Problem: sitelinks are sequenced:

Discussion: order the sitelinks, then include a hash of the link in the ID.  Add a sequence number in case of collisions.

**Comment by dgarijo** [comment]
@CraigMiloRogers what if there is a repeated qualifier? E.g., The units for a value are different, depending on the source of the statement. Then ordering qualifiers by qualifier property may be inconsistent, right?

**Comment by CraigMiloRogers** [comment]
This problem is mostly resolved.  We generate stable IDs that will change when the entry changes. The remaining problems are ID collisions, which seem  to mainly be due to instances where the KGTK data type system doesn't support Wikidata's dta type system.

**Comment by CraigMiloRogers** [comment]
I split the ID collisions into a new issue.
