### ISSUE TITLE
KGTK filter does not work in dev branch

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#159]
**Describe the bug**
The following cell from the example 5 notebook produces error:
```
!kgtk filter \
  --invert \
  -p ';ont:justifiedBy,ont:privateData,ont:system,ont:informativeJustification;' sample_data/aida/results/HC00001DO.ttl.unreified.tsv \
  > sample_data/aida/results/HC00001DO.ttl.unreified.nojust.tsv
```

produces:
```
Error: The pattern must have three sections separated by semicolons (two semicolons total).
Bad pattern
```
However, there are 2 semicolons as requested.

**To Reproduce**
This notebook does not work (built on dev branch)
https://mybinder.org/v2/gh/usc-isi-i2/kgtk/dev?filepath=examples%2FExample5%20-%20AIDA%20AIF.ipynb

**Expected behavior**
This notebook, pointing to master branch, works:
https://mybinder.org/v2/gh/usc-isi-i2/kgtk/master?filepath=examples%2FExample5%20-%20AIDA%20AIF.ipynb

**Comment by CraigMiloRogers** [comment]
The input file should come first, or it should be preceeded by `-i` or `--input-file`.

**Comment by dgarijo** [comment]
Thanks, I will assign part of the issue to myslef to fix all notebooks with filter

**Comment by dgarijo** [comment]
Since all notebooks have been adapted, this issue has been fixed in the `dev` branch. Thanks @CraigMiloRogers !
