### ISSUE TITLE
Update documentation for generate_wikidata_triples

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#168]
https://kgtk.readthedocs.io/en/latest/export/generate_wikidata_triples/

specifically,

```
cat input_file.tsv input_file.tsv | kgtk generate_wikidata_triples -w yes -pd yes > output_file.ttl
```
input_file.tsv is repeated for cat

**Comment by dgarijo** [comment]
I fixed this in dev.

**Comment by saggu** [comment]
Ah, I see. Thanks @dgarijo . Closing this issue then

**Comment by dgarijo** [comment]
(I did it based on the issue, since it was a super quick fix)
