### ISSUE TITLE
`kgtk sort2` generates `Illegal option -u` error

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/kgtk#172]
On the `dev` branch `kgtk sort2` command generates `/bin/sh: 1: read: Illegal option -u` error on Ubuntu. This does not happen with the `sort` command

```
$ kgtk sort2 -i all.everything.tsv.gz | gzip > all.everything-sorted.tsv.gz
/bin/sh: 1: read: Illegal option -u
$ kgtk sort -i all.everything.tsv.gz | gzip > all.everything-sorted.tsv.gz
$
```

**Comment by CraigMiloRogers** [comment]
Interesting. Do you happen to know which default shell you are using?

**Comment by kyao** [comment]
I use bash

**Comment by CraigMiloRogers** [comment]
I'll explicitly requore bash.
