### ISSUE TITLE
Text-embedding labels not generated properly

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#179]
**Describe the bug**
`kgtk text-embedding` generates sentences that use the edge label rather than its value (node2):
```/c/en/10_downing_street	embedding_sentence	10 downing street is label, label label.```

**To Reproduce**

```
kgtk text_embedding \
    --debug --embedding-projector-metadata-path none \
    --embedding-projector-metadata-path none \
    --label-properties "label" \
    --isa-properties "/r/IsA" \
    --description-properties "/r/DefinedAs" \
    --property-value "/r/Causes" "/r/UsedFor" "/r/PartOf" \
    --has-properties "" \
    -f kgtk_format \
    --output-data-format kgtk_format \
    --model bert-large-nli-cls-token \
    --save-embedding-sentence \
    -i sorted.tsv \
    -p sorted.tsv \
    > cskg_embedings.txt
```
**Expected behavior**
The expected output for the above sentence should have been:
```/c/en/10_downing_street	embedding_sentence	10 downing street is building and part of london.```

**Desktop (please complete the following information):**
 - OS Catalina 10.15

**Comment by CraigMiloRogers** [comment]
The problem derives from `get_real_label_name(node)` in `gt/embeddings_utils.py`, which returns `node` if `node` is not found in `self.node_labels.

**Comment by CraigMiloRogers** [comment]
Several callsites are involved:

attribute_dict["description_properties"][0]
self.get_real_label_name(node_value)
temp_list: typing.List[str] = [self.get_real_label_name(each) for each in attribute_dict["has_properties_values"]]
attribute_dict["isa_properties"]

In each of these cases, the code doesn't appear to consider the case that a label isn't available.

**Comment by CraigMiloRogers** [comment]
I could make the code not generate an output sentence when these slots cannot be filled. Is that acceptable?

**Comment by saggu** [comment]
@CraigMiloRogers is the problem is that the label is not present for a Qnode, then @filievski can update his input file for labels to include that

**Comment by saggu** [comment]
The code is behaving correctly, if the label is not present, return the node.

**Comment by CraigMiloRogers** [comment]
The node is "label", which then appears in the output, which @filievski complained about.

**Comment by CraigMiloRogers** [comment]
OK, what if I make the code give some feedback to aid @filievski in updating his label files?

**Comment by saggu** [comment]
@filievski is saying that instead of using the value from the column, `node2`, the code is instead using the value from column `label`. I think text embedding has an incorrect index for column `node2`.

@CraigMiloRogers do you the input files to test it out ?

**Comment by CraigMiloRogers** [comment]
Yes, I just reached the same understanding. Another error in my hasty conversion to use KgtkReader. Need a unit test.

**Comment by CraigMiloRogers** [comment]
Fixed, I think.
