### ISSUE TITLE
`text-embedding` should be: 1) split into `node-sentences` and `text-embedding`; 2) made easier to use (less compulsory parameters)

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#181]
The `text-embedding` command now generates sentences and computes embeddings. Having the sentences pre-computed is preferred. 

The `node-sentences` command would take a KGTK file as input and output a sentence for each node. The text-embedding parameters that choose relations for the sentences should go to this command. This command does not need to be parallelized.

The `text-embedding` command would merely compute embeddings, and have arguments such as dimensionality and embedding model.

Once this is ready, we should also fix the parallelization of text-embedding.

In addition, we need to rethink/redesign the command in terms of parameters. The user is now expected to set 5-10 parameters even for a default run - can we somehow set defaults for as many as possible of these?

**Comment by CraigMiloRogers** [comment]
This issue has been superseded y issue #237.
