### ISSUE TITLE
Rename wikidata types to be consistent with Wikidata SPARQL endpoint

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#183]
The Wikidata SPARQL endpoint uses the following names:
```
WikibaseItem
CommonsMedia
ExternalId
String
Quantity
Time
Monolingualtext
Url
Math
GeoShape
WikibaseSense
WikibaseLexeme
MusicalNotation
WikibaseProperty
TabularData
GlobeCoordinate
WikibaseForm
```

**Comment by CraigMiloRogers** [comment]
@szekely The wikidata types we use, both in the imported data and in the files names, are what appear in the Wikidata JSON file. They are the values that appear in the wikidata documentation: https://www.wikidata.org/wiki/Help:Data_type

**Comment by szeke** [comment]
Are you saying that the specific names you use appear in the JSON file? If that is the case, it is unfortunate, as the names I put in the issue are the names used in the SPARQL endpoint.

**Comment by CraigMiloRogers** [comment]
Yes, the specific names I use are the ones that appear in the JSON file.  They are documented in: https://www.wikidata.org/wiki/Help:Data_type

**Comment by CraigMiloRogers** [comment]
I've been looking for straightfoward translation between these datatypes and the SPARQL datatypes in the online documentation.  I haven't found one yet.  The Wikidata SPARQL documentation seems incomplete.

**Comment by CraigMiloRogers** [comment]
The Wikidata RDF dump format uses the same property types as the JSON dump format.  This is documented in https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format#Value_representation

**Comment by CraigMiloRogers** [comment]
When reading these documents, it is important to keep in mind that there are *two* datatype systems:  the datatype of the property, and the datatype of the property's value. For example, External Ids are associated with property type `external-id` and value type `string`.  As far as I can tell, the value type identifies the lexical parser to use when reading the value, while the property datatype represents the more formal datatype.

**Comment by szeke** [comment]
The specific issue is the format used for the following:
```
WikibaseItem
CommonsMedia
ExternalId
String
Quantity
Time
Monolingualtext
Url
Math
GeoShape
WikibaseSense
WikibaseLexeme
MusicalNotation
WikibaseProperty
TabularData
GlobeCoordinate
WikibaseForm
```
The names above are the names used in the SPARQL endpoint. The names you use appear in the JSON dump?

**Comment by CraigMiloRogers** [comment]
Yes, the names I use appear in the JSON dump.

**Comment by CraigMiloRogers** [comment]
@szeke In your list of labels, is `GlobeCoordinate` really supposed to be `Globecoordinate`? If so, then I understand there these Identifiers come from.  They are the wikibase:PropertyType values that appear in the `.ttl` (RDF) export files.

**Comment by szeke** [comment]
Sigh, can we list both names in the file, using two properties, listing both spellings. They made it harder for us.

**Comment by CraigMiloRogers** [comment]
The ontology file, http://wikiba.se/ontology# , lists most of thes...but not MusicalNotation.  It's not in the published ontology.  However, the published ontology mentions that there are extensions, using Math as an example.  I susoect MusicalNotation is another extension.

**Comment by szeke** [comment]
We want to support all the types that are present in the dump

**Comment by CraigMiloRogers** [comment]
Which I am doing empirically, by looking at all the types present in the dump.  We need to be alert in case new types are added.

**Comment by CraigMiloRogers** [comment]
Would it be sufficient to have a translation file that translates the JSON dump names (used by `kgtk import-wikidata`) to the TTL dump names (used by the SPARQL endpoint)?

**Comment by CraigMiloRogers** [comment]
I have to build such a file before lifting the SPARQL names as labels into other rows.

**Comment by CraigMiloRogers** [comment]
```
node1   label   node2
commonsMedia    sparql-porperty CommonsMedia
external-id     sparql-property ExternalId
geo-shape       sparql-property GeoShape
globe-coordinate        sparql-property Globecoordinate
math    sparql-property Math
monolingualtext sparql-property Monolingualtext
musical-notation        sparql-property MusicalNotation
quantity        sparql-property Quantity
string  sparql-property String
tabular-data    sparql-property TabularData
time    sparql-property Time
url     sparql-property Url
wikibase-form   sparql-property WikibaseForm
wikibase-item   sparql-property WikibaseItem
wikibase-lexeme sparql-property WikibaseLexeme
wikibase-property       sparql-property WikibaseProperty
wikibase-sense  sparql-property WikibaseSense
```

**Comment by CraigMiloRogers** [comment]
I've pushed this file into `dev`: `wikidata/wikidata-sparql-property-names.kgtk`.

**Comment by CraigMiloRogers** [comment]
Closing this issue. If we need to lift the SPARQL names into a column in certain files, we'll create a new issue.
