### ISSUE TITLE
Simplify Wikidata parts, remove part.property.*

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#185]
The current partitioning creates separate files for node1s that are properties. This distinction is unnecessary as it is easy to identify properties using the `property.datatype.tsv` file

**Comment by CraigMiloRogers** [comment]
@szeke Do you really want me to remove the file with the property labels?

**Comment by szeke** [comment]
Good catch, it is no longer red and scratched out

**Comment by CraigMiloRogers** [comment]
Done in the new partition-wikidata Jupyter notebook.
