### ISSUE TITLE
All Wikidata parts should be sorted by node1

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#189]
Some of the expensive processing commands such as `ifnotexists` demand sorted files for efficiency. We might as well publish all files in `node1/label/node2/id order` (or whatever is the default order in `sort2`

**Comment by CraigMiloRogers** [comment]
On the other hand, the qualifier extraction step in partition-wikidata relies on matching `node1` in the full `qual` file with `id` in the parts (`string`, etc.).  This works when the parts are sorted by `id` first. but would not work when the parts are sorted by `node1/label/node2/id`, on account of the hashing that has been introduced to keep IDs short.

**Comment by CraigMiloRogers** [comment]
We may need multiple sorts of the partitioned data. In turn, I need a naming convention to distinguish them.  I think it would be safe to name the first column of the sort: `id` for `id/node1/label/node2` and `node1` for `node1/label/node2/id`.

**Comment by CraigMiloRogers** [comment]
Pedro has elected to sort the published parts by `id/node1/label/node2` without a special naming convention.
