### ISSUE TITLE
Create v4 of Wikidata with the 20200803 Wikidata dump

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#193]
Version 4 of the Wikidata dataset should use the simpler partitioning scheme where there are no separate files for properties. Also, the `all.tsv` file should contain all claims/statements in a Wikidata dump. The `v3 all.tsv` file does not contain the edges where node1 is a property

**Comment by CraigMiloRogers** [comment]
I hope to mane `all.tsv` contain all edges, including aliases, labels, descriptions, sitelinks, datatypes, and the extra edges needed to export a new Wikidata JSON file. In this scheme, `part.claims.tsv` should contain all edges except aliases, labels, descriptions, sitelinks, datatypes, etc.

**Comment by CraigMiloRogers** [comment]
I'm uploading the new import.

**Comment by dgarijo** [comment]
Google drive link?
Thanks!

**Comment by CraigMiloRogers** [comment]
The last few files are uploading.
