### ISSUE TITLE
Create a partition-wikidata Jupyter notebook.

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#194]
Convert the partition-wikidata shell scripts into a Jupyter notebook, which should include documentation.

The input file is a single KGTK edge file containing a complete set of Wikidata edges: claims, qualifiers, aliases, labels, descriptions, labels, sitelinks, and optionally the other edges needed to expert the Wikidata as a JSON file again.

**Comment by CraigMiloRogers** [comment]
TODO: Change the output file names to ones agreed to on 10-Nov-2020.

**Comment by CraigMiloRogers** [comment]
I think it's complete.  I'll close the issue, and reopen it if @szeke wants further changes.

**Comment by szeke** [comment]
The current implementation lists as assumptions that the input data must contain `rank`, `node2;wikidatatype` and `lang` columns. In the typical use case these columns are not available, so the notebook should be updated accordingly. It is more reasonable to require the `metadata.property.datatypes.tsv` information is in the input file, and needs to be pulled out first. A simple `kypher` query can do that.

I am not sure what to do about sitselinks, but we should not require a `lang` column.

**Comment by CraigMiloRogers** [comment]
I envisioned that the typical use case would be to split apart a file that originated as a reduction of the output of `kgtk import-wikidata`. If we augment the data from other sources, the augmented data will still have to comply with the the requirements for `kgtk export-wikidata` if we want to export it that way, until `kgtk export-wikidata` is changed.

As noted in the script, the `rank` column isn't actually used in the script, so that's not important.

The edge records for `metadata.property.datatypes.tsv` are split out using `kgtk filter` before the partition by Wikidata property datatype, so there shouldn't be a need to use `kypher` to extract them.  I do, however, want to check for completeness:  are there any inconsistencies between `metadata,property.datatypes.tsv`  and `node2;wikidatatype` contents?  They do, after all, come from different parts of the Wikidata JSON dump file.

I can work around the `lang` column and `sitelinks` issue by splitting `sitelinks` into two files.  `kgtk import-wikidata` already generates secondary edges on the `sitelinks` edges, including `sitelink-language` records which can be used to filter out the English language edges and their secondary edges.

**Comment by szeke** [comment]
Even when the file to be split is a subset of wikidata, the scripts that build the subset don't carry over the other columns. For example, the scripts use the derived P279star file, which does not have the extra columns.

**Comment by CraigMiloRogers** [comment]
I've added code to lift Wikidata Property Dataypes from "datatype" edge records into the "node2;wikidatatype" field in the claims records.  I am waiting for free resources on my workstation to test the new code.

**Comment by CraigMiloRogers** [comment]
I am testing.

**Comment by CraigMiloRogers** [comment]
The new code didn't fail when run with wikidata-20201130 as input.  It should be run with Pedro's dataset next.

**Comment by CraigMiloRogers** [comment]
The new code ran when forced to lift node2;wikidatatype.
