### ISSUE TITLE
Fix, Fork, Fake, or Forget Pyrallel

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#195]
`kgtk import-wikidata` requires a version of pyrallel that incorporates various bug fixes and enhancements. This version has been in the `dev` branch of the usc-isi-is/pyrallel GitHub repository since September 2020. Prior to making a new, clean release of the current KGTK software, one of the following actions should take place:
 1) The pyrallel repository merges its `dev` branch into its `master` branch and make a new release in pypy. The `kgtk` repository should specify that release in its requirements file.
2) The pyrallel repository is forked. The forked repository merges its `dev` branch into its `master` branch and issues a release to pypy.  KGTK repository changes its requirements file to request the forked repository.
3) The KGTK repository incorporates the improved pyrallel code directly in the KGTK repository and removes `pyrallel.lib` from the KGTK repository's requirements file.
4) `kgtk import-wikidata` abandons pyrallel.

**Comment by GreatYYX** [comment]
Sorry I forgot about this. There are still some issues left: e.g., older python version (< 3.8) compatibility. Maybe it can have a special release branch only for KGTK.

**Comment by CraigMiloRogers** [comment]
I've created a pull request with a proposed fix for the compatibility issue. I've tested the fix under Python 3.8 and the shared memory code still works.  I don't have a good setup to test it under an earlier version of Python.

**Comment by CraigMiloRogers** [comment]
(The pull request is in the pyrallel GitHub repository.)

**Comment by dgarijo** [comment]
@GreatYYX please review and merge when possible.

**Comment by CraigMiloRogers** [comment]
I improved the documentation regarding chunk_size, maxsize, and the serialized message size.  I added two new symbolic constants for the default chunk size and default maxsize. I fixed typos in the documentation.

**Comment by CraigMiloRogers** [comment]
I created a new pull request for @GreatYYX to review.

**Comment by CraigMiloRogers** [comment]
pyrallel.lib 0.0.9 was released.
