### ISSUE TITLE
Check for Missing Entity Definitions, etc. in a Wikidata Import

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#196]
Check whether all Wikidata entities in the label and node2 columns of the claims and qualifiers have a matching claim in the node1 column.  In particular, verify this for properties. For those entities that do not have a defining claim, check if they have a label.

Other things to check:
 - Are there qualifiers without matching claims?
 - Are there aliases, descriptions, labels, or sitelinks without matching claims?
 - Are there claims without matching aliases, descriptions, labels, or sitelinks?
 - Are there aliases, descriptions, labels, or sitelinks that do not have English language versions?

**Comment by CraigMiloRogers** [comment]
Yes, there are properties that don't have claims.  There's even one property, P9, that doesn't have a label.

**Comment by szeke** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/1074599/99625008-1fef7080-29e4-11eb-88ee-afa2e33e453a.png">

**Comment by szeke** [comment]
Does `P9` have some indication in the JSON that it should not exist?

**Comment by CraigMiloRogers** [comment]
Here's what happened.  There's code in `import_wikidata.py`, from the original author, that rejects claims for any entity that has a P31 or P279 relationship to any of the following properties:
```

id      id;label
Q10617810       'punctuation mark'@en
Q11266439       'Wikimedia template'@en
Q13406463       'Wikimedia list article'@en
Q1383557        'intra-word punctuation'@en
Q15407973       'Wikimedia disambiguation category'@en
Q163875 'cardinal number'@en
Q17907810       'letter having circumflex'@en
Q18616576       'Wikidata property'@en
Q188725 'ligature'@en
Q191780 'ordinal number'@en
Q19776628       'Latin-script letter'@en
Q19887878       'Wikimedia infobox template'@en
Q224414 'Category'@en
Q22808320       'Wikimedia human name disambiguation page'@en
Q23894233       'Wikimedia templates category'@en
Q33120876       'Wikimedia content project'@en
Q3841820        'consonant letter'@en
Q4167410        'Wikimedia disambiguation page'@en
Q4167836        'Wikimedia category'@en
Q42104522       'Wikimedia category (disambiguation)'@en
Q4663903        'Wikimedia portal'@en
Q47460393       'type of number'@en
Q64875536       'Wikimedia disambiguation page'@en
Q66480449       'Wikimedia surname disambiguation page'@en
Q9398093        'vowel letter'@en
Q9788   'letter'@en
```

**Comment by CraigMiloRogers** [comment]
That's what caused the missing properties to go missing.  It may have caused items (Qxxx) to go missing, too.

**Comment by CraigMiloRogers** [comment]
I've added an option to disable this filter.  I'll re-import wilidata-20200803 with the filter disabled.

**Comment by CraigMiloRogers** [comment]
P31 is "instance of"
P279 is "subclass"

**Comment by CraigMiloRogers** [comment]
Reopened until I have confirmed with a complete import that the problems has been solved.

**Comment by CraigMiloRogers** [comment]
Pedro said to remove the P31/P279 statement rejection code entirely.

**Comment by CraigMiloRogers** [comment]
Remove the P31/P279 filtering in issue #254
