### ISSUE TITLE
Text-embedding sentences not always correctly generated

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#211]
**Describe the bug**

The sentences generated by `kgtk text-embedding` are more often than not having nodes instead of labels. Comparing the cases when nodes were rendered to those when the labels were found, I was not able to find any obvious reason for it. In both cases, the labels exist in the graph.

Example:
`/c/en/0_degrees_celcius	embedding_sentence	0 degrees celcius, point at which water freezes.` works well, but not `/c/en/0_degress_farenheit	embedding_sentence	0 degress farenheit Wikidata property /c/en/appliance_store.`

One observation is that most of the ConceptNet lexical nodes work well, whereas most (or all) WordNet nodes (e.g., `/c/en/medical_school/n/wn/group`) don't.

**To Reproduce**

```
#/bin/sh

f="cskg/cskg_connected_normalized.tsv.gz"

kgtk text_embedding \
    --embedding-projector-metadata-path none \
    --label-properties "label" \
    --isa-properties "/r/IsA" \
    --description-properties "/r/DefinedAs" \
    --property-value "/r/Causes" "/r/UsedFor" "/r/PartOf" "/r/AtLocation" "/r/CapableOf" \
    "/r/CausesDesire" "/r/SymbolOf" "/r/MadeOf" "/r/LocatedNear" "/r/Desires" "/r/HasProperty" "/r/HasFirstSubevent" \
    "/r/HasLastSubevent" "at:xAttr" "at:xEffect" "at:xIntent" "at:xNeed" "at:xReact" "at:xWant" \
    --has-properties "" \
    --use-cache \
    -f kgtk_format \
    --save-embedding-sentence \
    --output-data-format kgtk_format \
    --model bert-large-nli-cls-token \
    -i $f \
    -p $f \
    > cskg_embeddings.txt
```

**Expected behavior**
As nearly all nodes have labels, I'd expect that nearly all sentences should be fully in natural text.

**Comment by CraigMiloRogers** [comment]
In the example Filip gave above `/c/en/appliance_store` should have been some label text.

**Comment by filievski** [comment]
@CraigMiloRogers This is the line in the graph that contains the label:
```
	/c/en/appliance_store	label	"appliance store"			
```
I note that the labels have an empty id, but Amandeep said earlier that this should not be an issue for the text-embedding command.

**Comment by CraigMiloRogers** [comment]
Before I converted `kgtk text-embedding` to use KGTK input files, the --property-labels-file had a different format.  There were two columns, called "predicate" and "label", and the file was supposed to contain *only* labels. The new format reads a KGTK file with the "node1" column containing what used to be "predicate", and the "node2" column containing what used to be "label".

**Comment by CraigMiloRogers** [comment]
In the example command shown at the top of the issue, the same file is fed as both input ("-i $f") and as the property label file ("-p $f"). This is incorrect, as the input file has rows other than property labels.  The presence of these rows was causing problems .

**Comment by CraigMiloRogers** [comment]
I'm adding a new option , `--property-labels-filter`, with a default of ["label"]. You may note that this is the same as the default value for "--label-properties", and it is possible that I should just use the value(s) for `--label-properties` instead of introducing a new option.

This option lists the values of the "label" column of the property label file that will be considered label records when reading the property label file.

**Comment by CraigMiloRogers** [comment]
Another problem is the ordering of the labels.  The label that will be used is, in priority order:
1) the last label that is tagged as English, otherwise
2) the first label that is not tagged as English.

These rules predate conversion of `kgtk text-embedding` to use KgtkReader.

**Comment by CraigMiloRogers** [comment]
In "cskg_connected_normalized.tsv", the following lines appear:

        /r/HasProperty  label   "Wikidata property"
        /r/HasProperty  label   "has property"
        /r/HasProperty  label   "color"
        /r/HasProperty  label   "has quality"
        /r/HasProperty  label   "properties for this type"
        /r/HasProperty  label   "sex or gender"

The first two lines have to be swapped to get the desired output.  I can see that there might be times when the other definitions would be preferred, depending upon the words that follow, but I do not see how the present code would support that.

**Comment by CraigMiloRogers** [comment]
With these changes (filtering the property labels,  reordering the property labels), my debug writes show that we should see:
/c/en/0_degrees_farenheit --> 0 degrees farenheit has property very cold.

Note: There are spelling errors in "cskg_connected_normalized.tsv".  "celcius" should be spelled "celsius", and "farenheit"should be spelled "fahrenheit".

**Comment by CraigMiloRogers** [comment]
I've pushed the filtering option into the `dev` branch.

**Comment by CraigMiloRogers** [comment]
@filievski Please test.

**Comment by CraigMiloRogers** [comment]
@filievski Filip's initial testing indicates success.
