### ISSUE TITLE
Deploy the string query service

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#225]
Build the elastic search index for WikidataOS, and deploy to a server accessible outside ISI

**Comment by dgarijo** [comment]
@saggu,
I would be curious to test this setting and include it in the Docker image

**Comment by saggu** [comment]
https://dsbox02.isi.edu:5554/

VPN only for now

**Comment by saggu** [comment]
https://kgtk.isi.edu/search/, completed
