### ISSUE TITLE
Create KGTK file for KGTK properties

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#227]
In KGTK we create new properties to represent page rank, degree, etc. IN order to store them in the triple store we need to define them as properties in a KGTK file so that they can be put in the SPARQL endpoint.

The properties that need to be defined are in https://docs.google.com/spreadsheets/d/1Be7IwX_PlBW8-M6ADY64RbfelX3toWuFYY2l7GBa4J0/edit#gid=0

These properties must be included in the output directory.

**Comment by szeke** [comment]
@saggu Please update the TTL file in GitHub. Ideally, the TTL is computed in the notebook that needs them so that we can add to the TSV file without the burden to create the TTL file

**Comment by saggu** [comment]
Updated in commit https://github.com/usc-isi-i2/kgtk/commit/945b3177d7d5b6f9e28ae4f824b1fc0b842446cb
