### ISSUE TITLE
kgtk rename-columns does not allow whitespace in column headers.

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#243]
I think it should allow whitespaces, what is the reason it does not allow it? @CraigMiloRogers

**Comment by CraigMiloRogers** [comment]
I was opposed to allowing internal white space in column names because I expect that column names with internal white space will cause problems in command line parsing.

**Comment by CraigMiloRogers** [comment]
I've applied changes to allow whitespace in column names, with the option to prohibit it in KgtkReader.  The unit tests pass.
