### ISSUE TITLE
Exception when operating with Wikidata imported results

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#246]
In some cases, I see an exception similar to the one below:

```
KGTKException found
KgtkWriter: File PosixPath('deltas/delta20191007_20201012/added_filtered.tsv'): Required 4 columns ('id\tnode1\tlabel\tnode2')in output line 30307298, saw 18 (14 extra): 'Q98593815-P31-Q20747295-q98593815$8aa71134-421c-fafe-462d-05cadee72c80-0\tQ98593815\tP31\tQ20747295\tnormal\t\t\t\tQ20747295\t\t\t\t\t\t\titem\twikibase-item\t'
```

It looks like some rows are not properly imported, and have more columns than the ones KGTK is expecting.

**Comment by CraigMiloRogers** [comment]
@dgarijo Is this still happening?  If so, please provide me with an example.

**Comment by dgarijo** [comment]
Yes, after doing the filtering some files produced this exception. I will have to have a look for an example

**Comment by dgarijo** [comment]
I haven't found an example so far, so I will close this issue. However I found this several times. I will reopen when I get an example
