### ISSUE TITLE
Split a KGTK File into One File per Node1 Value

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#252]
For debugging KGTK operations, it would be helpful if we could automatically split a KGTK file into one file per node1 column value.

For extra credit, put Wikidata qualifiers in the same file as the claims edges they qualify.

**Comment by szeke** [comment]
@saggu has a script to split long KGTK files into chunks respecting node boundaries. I think it makes sense to generalize with an argument that specifies how many items per file

**Comment by saggu** [comment]
added `kgtk split` in `dev`
