### ISSUE TITLE
`kgtk import-wikidata` fails to complete

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#255]
@dgarijo reports a case in which `kgtk import-wiikidata` appears to hang.

20170227.json.gz

**Comment by dgarijo** [comment]
First time I ran the command I got:
```
The qual collector called 1000000 times: 0 nrows, 0 erows, 15052712 qrows
The node collector called 2500000 times: 25000000 nrows, 0 erows, 0 qrows
Bus error (core dumped)
```

I have also ran the import command with `20171113.json.gz`. It seems stuck. I see the program has dumped a `core.82` file in the folder where it's extracting the dump, and the files have not been written to disk in an hour.

**Comment by dgarijo** [comment]
For more information, this is how I ran the command ($line is a gz file):
```
kgtk import-wikidata \
        -i $line \
        --node "$folder_new_name"/nodefile.tsv \
        --edge "$folder_new_name"/edgefile.tsv \
        --qual "$folder_new_name"/qualfile.tsv \
        --use-mgzip-for-input True \
        --use-mgzip-for-output True \
        --use-shm True \
        --procs 12 \
        --mapper-batch-size 5 \
        --max-size-per-mapper-queue 3 \
        --single-mapper-queue True \
        --collect-results True \
        --collect-seperately True\
        --collector-batch-size 10 \
        --collector-queue-per-proc-size 3 \
        --progress-interval 500000
```

**Comment by CraigMiloRogers** [comment]
I ran with Daniel's command and JSON input file.  `kgtk import-wikidata` finished in 8 minutes on my workstation.

**Comment by dgarijo** [comment]
Uploaded `20171113.json.gz`, which was problematic for me

**Comment by CraigMiloRogers** [comment]
"problematic_dumps/20170227.json.gz", on the KGTK Wikidata Evolution Google Drive, the file Daniel provided to me, worked for Daniel, too.  He's uploading a different file, "problematic_dumps/20171113.json.gz".

**Comment by CraigMiloRogers** [comment]
"dumps/20171113.json.gz" import ran OK on my workstation. I'm trying "dumps/20170313.json.gz" now.

**Comment by dgarijo** [comment]
When there is an error, the thread just hangs for me (usually between 95%-99%). I wonder if it's an issue with the python version (3.8.6), or maybe the number of processors. I will play around with them, but this also happened when there was an error with the older import.

**Comment by CraigMiloRogers** [comment]
I'm testing code to detect missing attributes, report the problem, and continue importing what can be imported.

**Comment by dgarijo** [comment]
I reduced the number of processors (8) and now even though I see sometimes the datatype error, nothing hangs I haven't seen a core dump. So I am no longer blocked :) (except for the very early dumps)

**Comment by CraigMiloRogers** [comment]
I've merged a change into `dev` that should detect, report, and ignore certain missing data in the JSOn file.  This should help you import these files.

**Comment by dgarijo** [comment]
Thanks, I have updated my dev Docker image and will work on this from now on.

**Comment by CraigMiloRogers** [comment]
@dgarijo reports that his import now works.
