### ISSUE TITLE
node2;wikidatatype column not being created in partition-wikidata notebook

### ISSUE THREAD

**Issue by nicklein** [usc-isi-i2/kgtk#266]
**Describe the bug**
This issue is with the partition-wikidata notebook (in examples folder). In the "merge wikidata property datatypes into the claims" step of this notebook, I am expecting that the claims file will end up with a node2;wikidatatype column. It does not - it ends up with id node1 label node2 label;label. When I move on to the partitioning step, I get `Error: Cannot find the object column 'node2;wikidatatype'`, and it raises an exception.

**To Reproduce**
1. Here are parameters that I changed from the defaults:
`wikidata_input_path = os.path.abspath('../../Q154/data/all.tsv.gz')`
`wikidata_parts_path = os.path.abspath('../../Q154/data/parts')`
`presorted =           'True'`
`sort_extras =         '--buffer-size 30% --temporary-directory ' + temp_folder_path`

The all.tsv.gz file that I specified was created by the 'KGTK Tutorial' example notebook. I'll attach the file incase you want to try reproducing the issue with it - [all.tsv.gz](https://github.com/usc-isi-i2/kgtk/files/5691731/all.tsv.gz)

2. Run the notebook. Once you run the 'merge wikidata property datatypes into the claims' step, note that the output claims file doesn't have a node2;wikidatatype column.
3. Continue to run the notebook. Once you run the 'Partition the claims by Wikidata Property Datatype' step, see that an missing column exception is raised.

**Expected behavior**
I expected that an exception would not be raised by the partition step. Based on the error message I saw there, I would expect that the merge datatypes to claims step would create a column in the claims file called 'node2;wikidatatype'

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Additional context**
I thought the problem might be that the semicolon in 'node2;wikidatatype' at the end of the command is not escaped since I got the message `/bin/bash: wikidatatype: command not found`. I tried escaping it and the error went away, but still no node2;wikidatatype column.

**Comment by CraigMiloRogers** [comment]
There was a bug in `kgtk lift --columns-to-write` which sometimes caused the new column name to be ignored. This has been fixed in the `dev` branch.

**Comment by CraigMiloRogers** [comment]
There was a bug in `partition-wikidata.ipynb`. As described above, the new column name `node2;wikidatatype` needed to be escaped in the command line.

**Comment by CraigMiloRogers** [comment]
Also noted while working this problem is that the qualifiers must be included in the `partition-wikidata.ipynb` input file.

**Comment by CraigMiloRogers** [comment]
Tested OK.
