### ISSUE TITLE
Create Jupyter Notebook to document the filter command

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#271]
The notebook should document the capabilities of the command, the options and use small example TSV files that it loads from the repo to illustrate the different use cases/options

**Comment by dgarijo** [comment]
Probably the command 
```
kgtk filter -i $FILE -p " ; P31 ; " -o instanceOf.tsv 
```
Is one of the most useful ones

**Comment by CraigMiloRogers** [comment]
See also issue #113.

**Comment by szeke** [comment]
The markdown documentation is adequate, and the new tutorial contains examples
