### ISSUE TITLE
Error when doing kgtk filter + unique in old wikidata dumps (caused by import?)

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#272]
**Describe the bug**
I experience this bug with all the wikidata dumps I tried (so far) from earlier to 20160411. I manage to import and sort correctly, but when I execute:
```
kgtk filter -i test2.tsv -p " ; P31 ; " / unique --column node2 -o class_count.tsv
```
I get the following error:
```
KGTKException found
list index out of range
Line 9: Short row (len(row)=2, column_idx=2): ['', '+16100']
```
If I manually remove the lines from the file which are supposed to have the error, I get the following error:
```
KGTKException found
list index out of range
```
I am not sure very well how to proceed. It looks like the filter/count commands should continue, even though there is an exception in some rows

**To Reproduce**
1. Download https://drive.google.com/file/d/16Y0yAr93w2VHUd_q7SNtEy0sHRf39Ky5/view?usp=sharing
2. Import it using the kgtk import-wikidata command
3. Sort the file: `kgtk sort -i "$FILE" -c 'id' -o "$sorted_f"`
4. Execute `kgtk filter -i "$sorted_f" -p " ; P31 ; " / unique --column node2 -o class_count.tsv`
5. See error

**Comment by dgarijo** [comment]
I have dug into this and none of the P31 node2 seem to be imported:
```
P2268-P31-e3b0c442-p2268$6bc0e594-43b3-1af1-89da-df15bef2755b-0 P2268   P31             normal                      item     wikibase-item
```

**Comment by CraigMiloRogers** [comment]
Lots of records are missing node2 values.

Proposed approach:
1) Add a check for an empty node2 value on output, and reject the record.
2) Determine what is wrong with the JSON dump file, and reject the record on input.

**Comment by dgarijo** [comment]
Ouch, the problem is that I have detected that ALL P31 properties have an empty `node2`. So all my instance counts are empty

**Comment by dgarijo** [comment]
Detected this error for the following dumps: 
```
20160321
20160328
20160404
20160411
20160418
20160425
20160502
20160509
20160516
20160523
20160530
20160606
20160613
20160621
20160627
20160704
```
I did not try loading any before 20160321, so I guess all dumps before 20160704 have this error

**Comment by CraigMiloRogers** [comment]
The current Wikidata JSON dumps contain a Qxxx or Jxxx identifier in the 'id' field of wikibase entity snaks, as well as the numeric part of the identifier in the 'numeric-id' field. The older Wikidata JSON dumps contain only the 'numberid-ic' field.  I have changes `kgtk import-wikidata` to detect the missing `id` field and synthesize the correct value.

**Comment by CraigMiloRogers** [comment]
I have also added code to validate the output edge records in certain ways.
