### ISSUE TITLE
Wrong statements at the beginning of old sorted dumps 

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#275]
**Describe the bug**
Imported dumps from 2016 have strange characters at the beginning, which make counting/filtering fail:

```
id      node1   label   node2   rank    node2;magnitude node2;unit      node2;date      node2;item      node2;lower node2;upper      node2;latitude  node2;longitude node2;precision node2;calendar  node2;entity-type       node2;wikidatatype   lang
                                                quantity
                                                quantity
                                                quantity
                                                quantity
                                +16100
                                +25000
                                +5464
                                +6000
        +16100
        +25000
        +5464
        +6000
,+16100
,+25000
,+5464
,+6000
```
This leads to an exception when doing `kgtk filter -i "$sorted_f" -p " ; P31 ; " / unique --column node2 -o class_count.tsv`.

When manually removing the following lines:
```
                                                quantity
                                                quantity
                                                quantity
                                                quantity
                                +16100
                                +25000
                                +5464
                                +6000
        +16100
        +25000
        +5464
        +6000
,+16100
,+25000
,+5464
,+6000
```
And similar lines at the end of the file, everything works.

**To Reproduce**
1. Download https://drive.google.com/file/d/16Y0yAr93w2VHUd_q7SNtEy0sHRf39Ky5/view?usp=sharing
2. Import it using the kgtk import-wikidata command
3.  Sort the file: kgtk sort -i "$FILE" -c 'id' -o "$sorted_f"
4. Execute kgtk filter -i "$sorted_f" -p " ; P31 ; " / unique --column node2 -o class_count.tsv
5. See error

**Comment by CraigMiloRogers** [comment]
The JSON file contains newlines at the end of some supposedly numeric fields.

```      "P1083": [
        {
          "mainsnak": {
            "snaktype": "value",
            "property": "P1083",
            "datavalue": {
              "value": {
                "amount": "+16100\n",
                "unit": "1",
                "upperBound": "+16100\n",
                "lowerBound": "+16100\n"
              },
              "type": "quantity"
            },
            "datatype": "quantity"
          },
```

**Comment by dgarijo** [comment]
This happens for 40 dumps (20150805-20160502). I fixed it up by deleting those lines with a script (`sed`)

**Comment by CraigMiloRogers** [comment]
I'm making `kgtk import-wikidata` strip whitespace at the beginning or end of the numeric fields. I need to double check my work, then I'll merge the changes into `dev`.

**Comment by CraigMiloRogers** [comment]
Fix committed to `dev`.

**Comment by CraigMiloRogers** [comment]
Add protection against the numbers being encoded in JSON as numbers (makes sense).

**Comment by CraigMiloRogers** [comment]
Additional protection added.  There are still more places where additional paranoia is advisable, though.
