### ISSUE TITLE
add-id gives 'list index out of range'

### ISSUE THREAD

**Issue by nicklein** [usc-isi-i2/kgtk#276]
**Describe the bug**
When trying to use kgtk add-id to add in IDs to a kgtk file, I am getting a 'list index out of range' error...

I am up to date with the dev branch. Here is the command I am running: 
`kgtk --debug add-id -i $WORK/candidate_RAVLs_and_their_entities.tsv -o $WORK/candidate_RAVLs_and_their_entities.tsv --overwrite-id`

Here is the relevant input/output file: [candidate_RAVLs_and_their_entities.tsv.zip](https://github.com/usc-isi-i2/kgtk/files/5727138/candidate_RAVLs_and_their_entities.tsv.zip)

And here is the output:
`Traceback (most recent call last):
  File "/Users/nicklein/Documents/grad_school/Research.nosync/kgtk/kgtk/cli/add_id.py", line 125, in run
    idb.process(kr, ew)
  File "/Users/nicklein/Documents/grad_school/Research.nosync/kgtk/kgtk/reshape/kgtkidbuilder.py", line 495, in process
    kw.write(self.build(row, line_number))
  File "/Users/nicklein/Documents/grad_school/Research.nosync/kgtk/kgtk/reshape/kgtkidbuilder.py", line 400, in build
    if row[self.old_id_column_idx] != "" and not self.options.overwrite_id:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicklein/Documents/grad_school/Research.nosync/kgtk/kgtk/exceptions.py", line 46, in __call__
    return_code = func(*args, **kwargs) or 0
  File "/Users/nicklein/Documents/grad_school/Research.nosync/kgtk/kgtk/cli/add_id.py", line 136, in run
    raise KGTKException(str(e))
kgtk.exceptions.KGTKException: list index out of range
list index out of range`

**To Reproduce**
1. Download the above linked file and uncompress it.
2. Change the above command to have the correct path to the downloaded file.
3. Run the command and see that there is an error.

**Expected behavior**
I expected this to overwrite the id column of the input/output file with KGTK-compliant IDs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
If I change the output file to have a different name (i.e. not the same as the input file), then I don't get this error.

**Comment by CraigMiloRogers** [comment]
The sample command given above, 
```kgtk --debug add-id -i $WORK/candidate_RAVLs_and_their_entities.tsv -o $WORK/candidate_RAVLs_and_their_entities.tsv --overwrite-id```
appears to overwrite the input file with the output file.  That's not safe.

**Comment by CraigMiloRogers** [comment]
The problem was fixed in `dev` before the winter break.
