### ISSUE TITLE
Partition notebook fails on tutorial file

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#282]
Attached are the input file and the Jupyter notebook output. The failure is in cell 19

[all_and_qualifiers.tsv.gz](https://github.com/usc-isi-i2/kgtk/files/5773295/all_and_qualifiers.tsv.gz)

[partition-wikidata.out.ipynb.zip](https://github.com/usc-isi-i2/kgtk/files/5773299/partition-wikidata.out.ipynb.zip)

**Comment by CraigMiloRogers** [comment]
I copied the input KGTK file and the partition-wikidata notebook.  The notebook ran fine for me.  Here's how I invoked it, after creating `./parts/` and `./parts/temp/`: 
```
papermill \
    --progress-bar \
    --log-output --log-level DEBUG \
    ./partition-wikidata.ipynb \
    -p wikidata_input_path ./all_and_qualifiers.tsv.gz \
    -p wikidata_parts_path ./parts \
    -p temp_folder_path ./parts/temp \
    |& tee partition-wikidata.log
```

**Comment by CraigMiloRogers** [comment]
@szeke Can you provide me with a copy of the input file that fails in step 19?
 `/Users/pedroszekely/Downloads/kypher/wikidata_os_v5/parts/claims.tsv.gz`
I'd also like to see the predecessors to that file:
`/Users/pedroszekely/Downloads/kypher/wikidata_os_v5/parts/temp/claims.no-datatype.tsv.gz`
`/Users/pedroszekely/Downloads/kypher/wikidata_os_v5/parts/metadata.property.datatypes.tsv.gz`
`

**Comment by CraigMiloRogers** [comment]
@szeke pulled from github and the notebook worked.
