### ISSUE TITLE
What is ATOMIC?

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#291]
In this documentation page: https://kgtk.readthedocs.io/en/latest/import/import_atomic/ there is a command for importing ATOMIC.
However, it does not explain what it is, where does it come from or why is it relevant or interesting.
I think that it should be properly documented.

**Comment by filievski** [comment]
Good catch. I will document this.

**Comment by filievski** [comment]
Addressed on [dev](https://github.com/usc-isi-i2/kgtk/commit/357168044558dbabfd614fbdc2e331abc79afdb4). Closing.
