### ISSUE TITLE
Heisman trophy query returns no data in Wikidata OS SPARQL

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#300]
The following query performed in our SPARQL endpoint https://dsbox02.isi.edu:8888/wikidataos returns no results:
```
SELECT ?time ?c1 ?c2
WHERE 
{
  ?c1 wdt:P413 ?c2 ;
      wdt:P31 wd:Q5 .
  ?c2 wdt:P31/wdt:P279* wd:Q694589 .
  wd:Q1035067 p:P1346 ?s .
  ?s ps:P1346 ?c1 .
  ?s pq:P585 ?time .
 
}
ORDER BY ?time
```

The same query in the official wikidata returns all the desired result.

The equivalent cypher query on the KGTK files returns results, but no results after 2017, while the official wikidata returns the results until 2020:
```
!$kypher -i "$CLAIMS" -i "$LABEL" -i "$P279STAR" -i "$ISA" -i "$QUALIFIERS" \
--match '\
  claims: (c1)-[:P413]->(c2), \
  isa: (c1)-[isa]->(:Q5), \
  isa: (c2)-[]->(n2), P279star: (n2)-[:P279star]-(:Q694589), \
  claims: (c0:Q1035067)-[c4:P1346]->(c1), \
  qual: (c4)-[:P585]->(d0), \
  label: (c0)-[]->(c0_label), \
  label: (c1)-[]->(c1_label), \
  label: (c2)-[]->(c2_label)' \
--return 'distinct c0_label as award, c1_label as Player, c2_label as Position, d0 as Year' \
--order-by 'Year' 
```

The reason that we don't get the latest winners is that they were added to Wikidata in Jan 6, 2021:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/1074599/104799275-a45f3500-5782-11eb-8984-4f58a2ac4394.png">

**Comment by saggu** [comment]
Found the issue, this happened because we do not have time qualifiers in the generated triples. Time qualifiers were rejected because they have invalid ISO format.

```
Q1035067-P1346-Q736932-366117ab-0	Q1035067	P1346	Q736932	normal	wikibase-item
Q1035067-P1346-Q736932-366117ab-0-P585-f82fa0-0	Q1035067-P1346-Q736932-366117ab-0	P585	^1963-00-00T00:00:00Z/9time
Q1035067-P1346-Q7613529-a77c3d00-0	Q1035067	P1346	Q7613529	normal	wikibase-item
Q1035067-P1346-Q7613529-a77c3d00-0-P585-87910b-0	Q1035067-P1346-Q7613529-a77c3d00-0	P585	^1969-00-00T00:00:00Z/9		time
Q1035067-P1346-Q7614020-e0286b6e-0	Q1035067	P1346	Q7614020	normal	wikibase-item
Q1035067-P1346-Q7614020-e0286b6e-0-P585-6b2c71-0	Q1035067-P1346-Q7614020-e0286b6e-0	P585	^1966-00-00T00:00:00Z/9		time
Q1035067-P1346-Q7704079-0b0b45a5-0	Q1035067	P1346	Q7704079	normal	wikibase-item
Q1035067-P1346-Q7704079-0b0b45a5-0-P585-5da646-0	Q1035067-P1346-Q7704079-0b0b45a5-0	P585	^1962-00-00T00:00:00Z/9		time
```

I'll wait for @CraigMiloRogers  to clean the wikidata import. Here is the query which will work (wont return dates)

```
SELECT ?time ?c1 ?c2
WHERE 
{
  ?c1 wdt:P413 ?c2 ;
      wdt:P31 wd:Q5 .
  ?c2 wdt:P31/wdt:P279* wd:Q694589 .
  wd:Q1035067 p:P1346 ?s .
  ?s ps:P1346 ?c1 .
 # ?s pq:P585 ?time .
 
}
# ORDER BY ?time
```

**Comment by saggu** [comment]
Fixed in the latest version of DWD: 
http://ckg06.isi.edu:19001/#SELECT%20%3Ftime%20%3Fc1%20%3Fc2%0AWHERE%20%0A%7B%0A%20%20%3Fc1%20wdt%3AP413%20%3Fc2%20%3B%0A%20%20%20%20%20%20wdt%3AP31%20wd%3AQ5%20.%0A%20%20%3Fc2%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ694589%20.%0A%20%20wd%3AQ1035067%20p%3AP1346%20%3Fs%20.%0A%20%20%3Fs%20ps%3AP1346%20%3Fc1%20.%0A%20%20%3Fs%20pq%3AP585%20%3Ftime%20.%0A%20%0A%7D%0AORDER%20BY%20%3Ftime
