### ISSUE TITLE
`kgtk filter` Doesn't Allow `;` or `,` Inside Patterns

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#311]
`kgtk filter` doesn't include `;` or `,` inside patterns.

We could add a layer of quoting, but that would be a tremendous burden on normal use cases.

Let's add `--pattern-separator SEPARATOR` and `--word-separator SEPARATOR` options, allowing the use to supply alternative separators.

Pedro raised this issue.

**Comment by szeke** [comment]
I prefer to think of a more general solution rather than adding options to make filter work.

**Comment by dgarijo** [comment]
It also does not allow `^` (at least last time I tried updating the doc).

**Comment by CraigMiloRogers** [comment]
@dgarijo Show me an example.  My first guess is that your `^` needs to be quoted to prevent it from being treated as a shell metacharacter.
