### ISSUE TITLE
kgtk_lqstring_text_string returning extra "\"

### ISSUE THREAD

**Issue by summer7xinting** [usc-isi-i2/kgtk#329]
**Describe the bug**
When I try to generate node-to-label file using Kypher, I used kgtk_lqstring_text_string which removes language postfix but introduce a new backslash (see screenshot) if the label string contains a single quote (already escaped) 

**To Reproduce**
1. Download labels.en.tsv from [here](https://drive.google.com/drive/u/1/folders/1qbbgjo7pddMdDvQzOSeSaL6lYwj_f5gi)
2. Run `time kgtk query -i ~/dev/novartis/table-linker/SemTab2019/CEA/round_1/tableid2kgid_gt.tsv -i labels.en.tsv --graph-cache temp.sqlite2.db --match 'tableid2kgid_gt: (n1)-[]->(), labels: (n1)-[l:label]->(n2)' --return 'distinct n1 as node1, l.label as label, kgtk_lqstring_text_string(n2) as node2' -o ~/dev/novartis/table-linker/SemTab2019/CEA/round_1/node2label.tsv` to generate node2label.tsv

**Expected behavior**
`'Buffalo \'66'@en` should give us `Buffalo \'66`. See Q-node [here](https://www.wikidata.org/wiki/Q1002142)

**Screenshots**
Source file grep:
![image](https://user-images.githubusercontent.com/18204249/107077649-091a1800-67a2-11eb-9585-97055031f399.png)

File I generated from the cmd:
![image](https://user-images.githubusercontent.com/18204249/107077579-ea1b8600-67a1-11eb-9c56-d4d9c89f2348.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chalypso** [comment]
I pushed a fix to dev, let me know if it fixes the issue.

**Comment by summer7xinting** [comment]
Hi @chalypso so which commit is it that fixed issue 😂 I pulled dev but seems like the result has not changed on my end
<img width="747" alt="image" src="https://user-images.githubusercontent.com/18204249/107555967-ab644200-6b8c-11eb-8d86-62d7a8454f20.png">

**Comment by summer7xinting** [comment]
Hi @chalypso plz ignore my last comment! Seems like besides pulling dev, I need to `pip uninstall kgtk`, then run `pip install -e .` to get the right code base. The issue is fixed on my end 😊 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/18204249/107558995-5296a880-6b90-11eb-8daa-3802143b1287.png">

**Comment by chalypso** [comment]
Great, will close the issue.
