### ISSUE TITLE
Cannot query node properties, thus can't compute node2 in-degree.

### ISSUE THREAD

**Issue by mann-brinson** [usc-isi-i2/kgtk#338]
**Describe the bug**
kgtk query for node properties is not working as described in documentation. See [query doc](https://kgtk.readthedocs.io/en/latest/transform/query/#querying-connected-edges-through-graph-patterns) under 'Querying Connected Edges Through Graph Patterns'. As a result, I cannot query my node property `node2;wikidatatype`, and thus cannot compute in-degree properly.

![image](https://user-images.githubusercontent.com/40529252/107823010-e05ec900-6d33-11eb-9e51-abdbb23bf14a.png)

**To Reproduce**

1. Use claims.tsv.gz file as input. View the head
```
claims = 'claims.tsv.gz'
!zcat {claims} | head
```
```
###### RESULT #####
id	node1	label	node2	node2;wikidatatype	rank
P10-P1628-32b85d-7927ece6-0	P10	P1628	"http://www.w3.org/2006/vcard/ns#Video"	url	normal
P10-P1628-acf60d-b8950832-0	P10	P1628	"https://schema.org/video"	url	normal
P10-P1629-Q34508-bcc39400-0	P10	P1629	Q34508	wikibase-item	normal
P10-P1659-P1651-c4068028-0	P10	P1659	P1651	wikibase-property	normal
P10-P1659-P18-5e4b9c4f-0	P10	P1659	P18	wikibase-property	normal
P10-P1659-P4238-d21d1ac0-0	P10	P1659	P4238	wikibase-property	normal
P10-P1659-P51-86aca4c5-0	P10	P1659	P51	wikibase-property	normal
P10-P1855-Q7378-555592a4-0	P10	P1855	Q7378	wikibase-item	normal
P1000-P1629-Q1241356-d5c10f50-0	P1000	P1629	Q1241356	wikibase-item	normal
```

2. Calculate in-degree by only considering instances where node2 has wikidatatype = wikibaseitem.
```
kypher = "time kgtk --debug query"
!{kypher} -i {claims} \
--match '()-[l]->(n2 {`wikidatatype`:"wikibase-item"})' \
--return 'distinct n2 as node1, count(distinct l) as node2, "in_degree" as label' \
--order-by 'n2'
```
```
##### RESULT #####
/bin/bash: {kypher}: command not found
```

**Expected behavior**
This query should count in-degree for each node2, but only if node2 has wikidatatype = wikibaseitem.

**Environment**
This error was gained in conda environment set up on CKG06 (linux cent os 7).

**Comment by szeke** [comment]
This error has nothing to do with failure to produce correct results. your {} expansion is not working. We are not using {} expansion in the notebooks anymore as we found some interactions that produce errors. When you se an error fro `/bin/bash` it is a clue that your command is not running.
