### ISSUE TITLE
Add option to cat to sample edges

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#365]
Add an option to split an edge file randomly. A `--probability` argument specifies the probability that an edge is removed. Another parameter specifies a secondary file where the removed edges get stored. 

The purpose of this command is to generate a train/test split of an edge file.

**Comment by CraigMiloRogers** [comment]
The current sampling options are implemented in KgtkReader. I could add a probability-based sampling option, but I wouldn't be able to handle a reject file conveniently at that level of the code.

I'd prefer to create a new command, say, `kgtk sample`. 

Also, I'd prefer to make `--probability` be the probability of keeping an edge, so `--probability .1` keeps 10% of the edges.

**Comment by CraigMiloRogers** [comment]
Changes committed to `dev`.

**Comment by CraigMiloRogers** [comment]
Add options to compute the probability for n of N.  Added an option for an exact sample.

**Comment by CraigMiloRogers** [comment]
I figure out a better way to sample large files that doesn't require counting the length of the file first.

**Comment by CraigMiloRogers** [comment]
Changed pulled into `dev`.
