### ISSUE TITLE
Cannot find https://www.wikidata.org/wiki/Q35149 in the text search

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#373]
The problem here is that Wilhelm Röntgen does not have an alias with Wilhelm Rontgen, which is how one would search it.

We need to add aliases that convert the WD labels and aliases to ascii for the roman languages. Need to coordinate with Rijul to add these new strings to the index

**Comment by saggu** [comment]
Will add these to the second version of augmented wikidata dwd index

**Comment by saggu** [comment]
Fixed in latest version:  https://kgtk.isi.edu/search/
