### ISSUE TITLE
Query does not produce second column in the opt feature branch

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#381]
The following query does not populate the `class_label` column when the `labels` clause is optional:
```
!$kypher -i p31 -i labels -i "$TEMP"/movies.tsv \
--match ' \
    movies: ()-[]->(n2), \
    p31: (n2)-[l]->(class), \
    labels: (class)-[]->(class_label)' \
--return 'distinct n2 as node1, class_label' \
--order-by 'class_label' \
--limit 50
```

**Comment by chalypso** [comment]
Maybe your --limit 50 restricted you to only see the empty class labels?  If saving to a file doesn't fix the issue for you, I'll have to run on your exact data to see what's going on.

I ran the query like this and it seemed to do the right thing (I had to generate movies.tsv and p31 from my DWD browser DB instance):

`time kgtk --debug query -i p31 -i labels -i movies --index none --graph-cache wikidata-20210215-dwd-browser.sqlite3.db \
--match ' \
    movies: ()-[]->(n2), \
    p31: (n2)-[l]->(class)' \
--opt '\
    labels: (class)-[]->(class_label)' \
--return 'distinct n2 as node1, class_label' \
--order-by 'class_label' \
-o opt-query-labels.tsv.gz`

The initial section of the output looked like this:
`zcat opt-query-labels.tsv.gz | head -50
node1	node2
Q5207064	
Q340	
Q1510161	
Q46747	
Q26600	
Q37951	
Q735278	
Q34664	
Q1374418	
Q1048916	
Q156839	
Q5465	
Q2145	
Q5360808	
Q1336746	
Q53869288	
Q15279556	
Q1048268	
Q44012	
Q14169	
Q605879	
Q2625102	
Q28813	
Q19787925	
Q498211	
Q20970968	
Q10952958	
Q852697	
Q811686	
Q59639657	
Q60228128	
Q6695409	
Q830193	
Q16878157	'11月'@zh-cn
Q3345446	'11月'@zh-cn
Q13068515	'11月'@zh-cn
Q23790282	'15 rating'@en
Q4550895	'15 rating'@en
Q74434564	'15 rating'@en
Q26708078	'15 rating'@en
Q74434535	'15 rating'@en
Q22663448	'16 de septiembre'@es
Q22663448	'16 сентября'@ru
Q26708079	'18 rating'@en
Q237237	'1月'@zh-cn
Q20121517	'2016年美国总统竞选活动'@zh-cn
Q22664398	'22 de julio'@es
Q22664398	'22 июля'@ru
Q17172923	'2月'@zh-cn`

**Comment by szeke** [comment]
Aha, could be, I'll give it a try, thx

**Comment by chalypso** [comment]
Looks like that was the problem, closing for now.
