### ISSUE TITLE
reachable-nodes does not work when the roots file has a single column

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#382]
When the roots file has a single column, the file is rejected and the following error appears:
```
In root header 'node1': Missing required column: label | predicate | relation | relationship
/Users/pedroszekely/opt/anaconda3/envs/kgtk-env/lib/python3.7/site-packages/kgtk-0.5.0-py3.7.egg/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'SystemExit'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found
```

Not clear why it wants multiple columns in the roots file. The command should accept a file with multiple columns, and then the `--rootfilecolumn` specifies the column. If the file has a single column there is no need to specify `--rootfilecolumn`

This command is also using old names  `subj`, `pred`, `obj` to refer to the standard columns, these argument names should be consistent with the kgtk naming convention.

**Comment by CraigMiloRogers** [comment]
Well, the first thing I see is that the root file is read with a KftkReader, but the file name isn't parsed with the advanced argument parser.

**Comment by CraigMiloRogers** [comment]
Since the root file is being read by KgtkReader, it should be a KGTK Edge file or a KGT Node file.  Possibly, it might be neither, but since the argument parsing isn't done quite right, I'm not certain that's an option.

**Comment by CraigMiloRogers** [comment]
What matters most to the KgtkReader is whether there's a `node1` column. If so, then the file is assumed to be an Edge file, and the `label` and `node2` columns are required.  If there's no `node1` column, but there's an `id` column, then the file is assumed to be a Node file.

**Comment by CraigMiloRogers** [comment]
We don't have a convention that if the node file contains a single column, use that one.

**Comment by CraigMiloRogers** [comment]
So, one option you have is to rename the column name of your root file to be `id` instead of `node`, as a proper KGTK node file.

**Comment by CraigMiloRogers** [comment]
Another option is to use the available options:

`--root-mode=NONE --rootfilecolumn=node1`

**Comment by CraigMiloRogers** [comment]
@szeke I've improved the documentation for this command in the `dev` branch. Please reopen this issue if that isn't sufficient.
