### ISSUE TITLE
KGTK modulenotfound Error

### ISSUE THREAD

**Issue by jindalkanika** [usc-isi-i2/kgtk#384]
**Description**
I was trying to calculate the pagerank and degree using KGTK on wikidata. 
But it throws an error:
/usr/local/lib/python3.7/dist-packages/kgtk/exceptions.py:66: UserWarning: Please raise KGTKException instead of <class 'ModuleNotFoundError'>
  warnings.warn('Please raise KGTKException instead of {}'.format(type_))
KGTKException found

I have tried it on different OS (windows 10, macOs with mac having M1 chip) and google colab. I tried using docker image as well but this doesn't seem to go. 

Code I was trying to run:
!kgtk graph-statistics --log summary.txt --pagerank --statistics-only -i 'alcoholic_beverages_labels.tsv'

or 

!time kgtk graph_statistics --degrees --pagerank --log "summary.txt" -i "alcoholic_beverages_edges.tsv.gz" > "alcoholic-pagerank-degrees.tsv"

both throws same error.

**Comment by saggu** [comment]
@jindalkanika can you try to add the `--debug` option while running the command, like so

```
kgtk --debug graph-statistics --log summary.txt --pagerank --statistics-only -i 'alcoholic_beverages_labels.tsv'
```

Most likely you'll find `graph-tool` is not installed

**Comment by saggu** [comment]
No updates in 2 weeks. Closing.
