### ISSUE TITLE
kgtk import-ntriples discards triples with langtag

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#387]
**Describe the bug**

kgtk import-ntriples discards triples with langtag, for example:

<http://www.nima.puc-rio.br/lattes/1944208293448093#P690> <http://purl.org/dc/elements/1.1/title> "A TunÃ­sia, o Egito e nÃ³s"**@pt** .
<http://www.nima.puc-rio.br/lattes/1944208293448093#P698> <http://purl.org/dc/elements/1.1/title> "Sindicato e PolÃ­tica no Governo Dilma"**@pt** .
<http://www.nima.puc-rio.br/lattes/1944208293448093#P699> <http://purl.org/dc/elements/1.1/title> "Entrevista - Luiz Werneck Vianna: Novo ambiente nÃ£o permite que Dilma repita Lula"**@pt** .
<http://www.nima.puc-rio.br/lattes/1944208293448093#P692> <http://purl.org/dc/elements/1.1/title> "Mares nunca dantes navegados"**@pt** .
<http://www.nima.puc-rio.br/lattes/1944208293448093#P691> <http://purl.org/dc/elements/1.1/title> "Os sindicatos e o Estado"**@pt** .

**To Reproduce**

kgtk import-ntriples -i file_in.nt -o file_out.tsv --reject-file rejected.nt 

Use the examples of triples above

**Expected behavior**
Converter this triplo to kgtk format

**Comment by CraigMiloRogers** [comment]
I tried to use wget to download the example file, but got error 404.
```
(kgtk-env) 137% wget 'http://www.nima.puc-rio.br/lattes/1944208293448093'
--2021-05-24 15:46:47--  http://www.nima.puc-rio.br/lattes/1944208293448093
Resolving www.nima.puc-rio.br (www.nima.puc-rio.br)... 139.82.34.45
Connecting to www.nima.puc-rio.br (www.nima.puc-rio.br)|139.82.34.45|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-24 15:46:51 ERROR 404: Not Found.

(kgtk-env) 138%
```

**Comment by versant2612** [comment]
You can use the attached file (ntriples)

[lattes-prof.zip](https://github.com/usc-isi-i2/kgtk/files/6535496/lattes-prof.zip)

**Comment by CraigMiloRogers** [comment]
I've committed a fix in the `dev` branch.  `kgtk import-ntriples` now works with the supplied example, although there are potential limits, since the W3C specification for RDF 1.1 N-Triples references an IETF document that specifies a more general structure for language tags than is presently supported by the KGTK File Format specification.

**Comment by CraigMiloRogers** [comment]
Add documentation to the .md file.

**Comment by CraigMiloRogers** [comment]
@versant2612 These changes have been pushed to the `dev` branch of the KGTK GitHub code repository.  Can you verify that they work for you?

**Comment by versant2612** [comment]
@CraigMiloRogers it worked perfectly!
