### ISSUE TITLE
Unreify bibo:authorList

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#389]
**Describe the bug**
I am having difficult do unreify a set of triples linked to bibo:authorList concept from Bibo Ontology

**To Reproduce**
Consider the edge list bellow as the input file content

node1	label	node2
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x260	rdf:first	lattes:0001107478160614#author-idm45446371295536
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x260	rdf:rest	rdf:nil
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x261	rdf:first	lattes:0001107478160614#author-idm45446371296624
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x261	rdf:rest	XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x260
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x262	rdf:first	lattes:0001107478160614#author-idm45446371297792
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x262	rdf:rest	XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x261
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x263	rdf:first	lattes:0001107478160614#author-idm45446371299072
XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x263	rdf:rest	XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x262
lattes:0001107478160614#P74	bibo:authorList	XGj2jsg7YsmyZsfPHx28fpT:b6B5E6273x263

I used the command

kgtk -i input.tsv unreify-values --trigger-label rdf:rest --trigger-node2 rdf:nil   --value-label bibo:authorList --old-label bibo:authorList -o output.tsv

**Comment by CraigMiloRogers** [comment]
The `-i input.tsv` needs to be after the `unreify-values`:
```
kgtk unreify-values -i input.tsv --trigger-label rdf:rest --trigger-node2 rdf:nil --value-label bibo:authorList --old-label bibo:authorList -o output.tsv
```

**Comment by CraigMiloRogers** [comment]
@versant2612 I don't see the type of pattern in your input file that `kgtk unreify-values` can solve.  I'm afraid that I don't understand what you expect as a result. Please supply me with your expected unreified result for the input example you supplied above, and I'll see if I can understand it better.

**Comment by versant2612** [comment]
@CraigMiloRogers I mistook RDF Collection (rdf:List) for Reification. Sorry. 
I'll check if I have reification examples in my dataset.

**Comment by CraigMiloRogers** [comment]
Closing. We may want to create an unreify list command.
