### ISSUE TITLE
`kgtk import-ntriples` Does Not Support Comments

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#391]
The (W3C document on RDF 1.1 N-Triples)[https://www.w3.org/TR/n-triples/] defines optional comments that may appear after the full stop (".") at the end of a triple. `kgtk import-ntriples` currently would reject triples with comments. 

The simplest enhancement is to strip any comments found, with a summary count at the end of processing.  A more complex option would be to convert N-Triples comments into KGTK comments.

**Comment by szeke** [comment]
I agree, we should keep the data and throw away the comments

**Comment by CraigMiloRogers** [comment]
`kgtk import-ntriples` also wasn't allowing some white space possibilities.

**Comment by CraigMiloRogers** [comment]
`kgtk import-ntriples` now strips N-Triples comments and non-canonical white space.

**Comment by CraigMiloRogers** [comment]
Changes merged into `dev`
