### ISSUE TITLE
kgtk generate_wikidata_triples command not working

### ISSUE THREAD

**Issue by ZhiqiangJerryQiu** [usc-isi-i2/kgtk#399]
**Describe the bug**
I'm trying to use 
```
cat file.tsv file.tsv | pv | kgtk generate_wikidata_triples -pd yes --debug -n 1000000 > file.ttl
```
to generate triple file from kgtk file. Here is the error message received
```
Traceback (most recent call last):
  File "/nas/home/zqiu/anaconda3/envs/sqid_test/bin/kgtk", line 33, in <module>
    sys.exit(load_entry_point('kgtk', 'console_scripts', 'kgtk')())
  File "/nas/home/zqiu/kgtk/kgtk/cli_entry.py", line 314, in cli_entry
    ret_code = cli_entry_sequential_commands(args, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/nas/home/zqiu/kgtk/kgtk/cli_entry.py", line 238, in cli_entry_sequential_commands
    ret_code = cli_entry_pipe(commands, parsed_shared_args, shared_args, parser, sub_parsers, subparser_lookup, subparsers_built)
  File "/nas/home/zqiu/kgtk/kgtk/cli_entry.py", line 115, in cli_entry_pipe
    mod.add_arguments_extended(sub_parser, psa)
TypeError: add_arguments_extended() takes 1 positional argument but 2 were given
```
Running `kgtk generate_wikidata_triples --help`` gives the same error message.

I tested with both running `pip install -e .` in dev branch and `pip install kgtk` in a clean virtual environment.

Running on mind03 server at ISI.

**Comment by CraigMiloRogers** [comment]
I've pushed a correction onto the `dev` branch.

**Comment by ZhiqiangJerryQiu** [comment]
> Yes, the code n generate_wikidata_triples.py needs a small correction.
> 
> BTW, if `file.tsv` is a standard KGTK edge file, then using system `cat` to double it would put a duplicate header line in the middle of the output file. Ise `kgtk cat -i file.tsv file.tsv`.


Thanks for this suggestion. Do you mean correct it to the following command?
```
kgtk cat -i file.tsv file.tsv | pv | kgtk generate_wikidata_triples -pd yes --debug -n 1000000 > file.ttl
```

I was following the document for -pd option at https://kgtk.readthedocs.io/en/latest/export/generate_wikidata_triples, you might also want to update the doc there.
