### ISSUE TITLE
`kgtk import-ntriples` Not Recognizing Standard xsd Types

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#404]
Submitted by @filievski

The import-ntriples command does not seem to work for our infoboxes file. For instance, for the first line:

```
<http://dbpedia.org/resource/Autism>    <http://dbpedia.org/property/name>    "Autism"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> .
```

it gives us three lines (even after defining the prefix for dbpedia in the namespace-file):
```
node6PCwgEcAVDmgzVuB7hpU2j-1    dbpedia:structured_value    "Autism"
node6PCwgEcAVDmgzVuB7hpU2j-1    dbpedia:structured_uri    rdf:langString
dbpedia-resource:Autism    property:name   node6PCwgEcAVDmgzVuB7hpU2j-1
```

@szeke 

This result is correct. It created a blank node to hold the string and type. It is not ideal, as we should recognize the standard xsd types and not generate the structured value.

In this case we want:
```
dbpedia-resource:Autism    property:name   "Autism"
```

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes

**Comment by CraigMiloRogers** [comment]
http://www.w3.org/1999/02/22-rdf-syntax-ns

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/TR/2014/REC-rdf-schema-20140225/

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/TR/rdf11-primer/

**Comment by CraigMiloRogers** [comment]
As far as I can tell, the input data is invalid RDF, because the datatype indicator `^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString>` may never be specified explicitly.

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/TR/rdf11-concepts/

**Comment by CraigMiloRogers** [comment]
From the RDF 1.1 Concepts document:

```
A literal in an RDF graph consists of two or three elements:

    a lexical form, being a Unicode [UNICODE] string, which SHOULD be in Normal Form C [NFC],
    a datatype IRI, being an IRI identifying a datatype that determines how the lexical form maps to a literal value, and
    if and only if the datatype IRI is http://www.w3.org/1999/02/22-rdf-syntax-ns#langString, a non-empty language tag as defined by [BCP47]. The language tag MUST be well-formed according to section 2.2.9 of [BCP47].
```

Further:

```
Similarly, most concrete syntaxes represent language-tagged strings without the datatype IRI because it always equals http://www.w3.org/1999/02/22-rdf-syntax-ns#langString.
```

**Comment by CraigMiloRogers** [comment]
From the RDF 1.1 Primer section on N-triples:

```
Because string literals are so ubiquitous N-Triples allows the user to omit the datatype when writing a string literal. Thus, "Mona Lisa" in line 5 is equivalent to "Mona Lisa"^^xsd:string. In case of language-tagged strings the tag appears directly after the string, separated by a @ symbol, e.g. "La Joconde"@fr (the French name of the Mona Lisa).

Note

For technical reasons the datatype of language-tagged strings is not xsd:string but rdf:langString. The datatype of language-tagged strings is never specified explicitly.
```

**Comment by CraigMiloRogers** [comment]
@filievski Can upi determine why your input file was generated with an invalid N-Triple? Can this be corrected?  A better input line would be:

```
<http://dbpedia.org/resource/Autism>    <http://dbpedia.org/property/name>    "Autism" .
```

without any language tag, (implying the dayatype of `xsd:string`), or:

```
<http://dbpedia.org/resource/Autism>    <http://dbpedia.org/property/name>    "Autism"@en .
```

implying the datatype of `rdf:langString`.

**Comment by CraigMiloRogers** [comment]
If the RDF 1.1 N-Triples reference documents didn't prohibit them, I'd be game to parse either:

```
"Autism"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString>@en
```

or

```
"Autism"@en^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString>
```

**Comment by CraigMiloRogers** [comment]
I can engineer a workaround that would allow `kgtk import-ntriples` to process this input data, by either:

* assuming that the language is `en` (or some othe rdefault supplied by an option), or
* importing the data as a plain string without a language tag.

**Comment by CraigMiloRogers** [comment]
@filievski says that the input file is Turtle (.ttl) format.

**Comment by CraigMiloRogers** [comment]
Here's a Turtle specification:

https://www.w3.org/TR/turtle/

**Comment by CraigMiloRogers** [comment]
RDF Turtle format allows literal quoting sequences that are not allowed in RDF 1.1 N-Triples format.

```\' (U+005C) may not appear in any quoted literal except as part of an escape sequence. Other restrictions depend on the delimiter:

    Literals delimited by ' (U+0027), may not contain the characters ', LF (U+000A), or CR (U+000D).
    Literals delimited by ", may not contain the characters ", LF, or CR.
    Literals delimited by ''' may not contain the sequence of characters '''.
    Literals delimited by """ may not contain the sequence of characters """. 
```

**Comment by CraigMiloRogers** [comment]
```
If the literal's datatype IRI is not in the set of recognized datatype IRIs, then the literal value is not defined by this specification.
```

The list of recognized datatype IRI's is:
```
https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes
```

**Comment by CraigMiloRogers** [comment]
Another change I could make to `kgtk import-ntriples` would be to detect this error and report it, optionally filtering it out.

**Comment by CraigMiloRogers** [comment]
I created a new branch, `issue/404/import-ntriples-invalid-datatype-iris`

**Comment by CraigMiloRogers** [comment]
I committed a change to reject records with unknown datatype IRIs by default.  This can be changed with `--allow-unknown-datatype-iris`.

**Comment by BohuiZhang** [comment]
I also found a situation that the `import-ntriples` could treat `http://www.w3.org/2001/XMLSchema#double` which is `xsd:double` in the simple format. For example, import
`<http://dbpedia.org/resource/Alabama> <http://dbpedia.org/property/highestelev> "735.5"^^<http://www.w3.org/2001/XMLSchema#double> .` 
will produce
`dbpedia-resource:Alabama    property:highestelev    735.5`
but it will produce a node for things like `"4338"^^<http://www.w3.org/2001/XMLSchema#integer>`, a node with labels like `structured_uri` and `structured_value`.

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatype

**Comment by CraigMiloRogers** [comment]
https://www.w3.org/TR/xmlschema-2/

**Comment by CraigMiloRogers** [comment]
Here are the XMLSchema (xsd) datatypes for N-Triple literals that will be converted to KGTK numeric literals:
```
      '<http://www.w3.org/2001/XMLSchema#decimal>',
        '<http://www.w3.org/2001/XMLSchema#integer>',
        '<http://www.w3.org/2001/XMLSchema#int>',
        '<http://www.w3.org/2001/XMLSchema#short>',
        '<http://www.w3.org/2001/XMLSchema#byte>',
        '<http://www.w3.org/2001/XMLSchema#nonNegativeInteger>',
        '<http://www.w3.org/2001/XMLSchema#positiveInteger>',
        '<http://www.w3.org/2001/XMLSchema#unsignedLong>',
        '<http://www.w3.org/2001/XMLSchema#unsignedInt>',
        '<http://www.w3.org/2001/XMLSchema#unsignedShort>',
        '<http://www.w3.org/2001/XMLSchema#unsignedByte>',
        '<http://www.w3.org/2001/XMLSchema#nonPositiveInteger>',
        '<http://www.w3.org/2001/XMLSchema#negativeInteger>',
        '<http://www.w3.org/2001/XMLSchema#double>',
        '<http://www.w3.org/2001/XMLSchema#float>',
```

**Comment by CraigMiloRogers** [comment]
Here are the XMLSchema (xsd) datatypes for N-Triple literals that will be converted to KGTK strings:

```
       '<http://www.w3.org/2001/XMLSchema#string>',
        '<http://www.w3.org/2001/XMLSchema#normalizedString>',
        '<http://www.w3.org/2001/XMLSchema#token>',
        '<http://www.w3.org/2001/XMLSchema#language>',
        '<http://www.w3.org/2001/XMLSchema#Name>',
        '<http://www.w3.org/2001/XMLSchema#NCName>',
        '<http://www.w3.org/2001/XMLSchema#ENTITY>',
        '<http://www.w3.org/2001/XMLSchema#ID>',
        '<http://www.w3.org/2001/XMLSchema#IDREF>',
        '<http://www.w3.org/2001/XMLSchema#NMTOKEN>',
```

**Comment by CraigMiloRogers** [comment]
Here are the XMLSchema (xsd) datatypes for N-Triple literals that will be converted to KGTK strings:

```
       '<http://www.w3.org/2001/XMLSchema#string>',
        '<http://www.w3.org/2001/XMLSchema#normalizedString>',
        '<http://www.w3.org/2001/XMLSchema#token>',
        '<http://www.w3.org/2001/XMLSchema#language>',
        '<http://www.w3.org/2001/XMLSchema#Name>',
        '<http://www.w3.org/2001/XMLSchema#NCName>',
        '<http://www.w3.org/2001/XMLSchema#ENTITY>',
        '<http://www.w3.org/2001/XMLSchema#ID>',
        '<http://www.w3.org/2001/XMLSchema#IDREF>',
        '<http://www.w3.org/2001/XMLSchema#NMTOKEN>',
```

**Comment by CraigMiloRogers** [comment]
Here are the XMLSchema (xsd) datatypes for N-Triple literals that will be converted to KGTK strings:

```
       '<http://www.w3.org/2001/XMLSchema#string>',
        '<http://www.w3.org/2001/XMLSchema#normalizedString>',
        '<http://www.w3.org/2001/XMLSchema#token>',
        '<http://www.w3.org/2001/XMLSchema#language>',
        '<http://www.w3.org/2001/XMLSchema#Name>',
        '<http://www.w3.org/2001/XMLSchema#NCName>',
        '<http://www.w3.org/2001/XMLSchema#ENTITY>',
        '<http://www.w3.org/2001/XMLSchema#ID>',
        '<http://www.w3.org/2001/XMLSchema#IDREF>',
        '<http://www.w3.org/2001/XMLSchema#NMTOKEN>',
```

**Comment by CraigMiloRogers** [comment]
Here are the XMLSchema (xsd) datatypes for N-Triple literals that will be converted to KGTK strings:

```
       '<http://www.w3.org/2001/XMLSchema#string>',
        '<http://www.w3.org/2001/XMLSchema#normalizedString>',
        '<http://www.w3.org/2001/XMLSchema#token>',
        '<http://www.w3.org/2001/XMLSchema#language>',
        '<http://www.w3.org/2001/XMLSchema#Name>',
        '<http://www.w3.org/2001/XMLSchema#NCName>',
        '<http://www.w3.org/2001/XMLSchema#ENTITY>',
        '<http://www.w3.org/2001/XMLSchema#ID>',
        '<http://www.w3.org/2001/XMLSchema#IDREF>',
        '<http://www.w3.org/2001/XMLSchema#NMTOKEN>',
```

**Comment by CraigMiloRogers** [comment]
I decided to convert bare langString instances to KGTK strings, as this was simplest to implement.  If someone needs them to be converted to KGTK language-qualified strings, it would not be hard to add that option.

**Comment by CraigMiloRogers** [comment]
The discussion in today's KGTK Toolkit meeting revealed that the DBpedia tooklit dumps were currently filtered to English-only. As a contingency, I added the `--lang-string-tag` command option to import values with langString datatype as a KGTK language-qualified string with a specified language tag (and optional suffix).

**Comment by CraigMiloRogers** [comment]
Per the discussion in today's KGTK Toolkit meeting, added an option to prevent the generation of new namespace prefixes.

**Comment by CraigMiloRogers** [comment]
The original goal of this issue has been met.
