### ISSUE TITLE
`kgtk import-ntriples` Should Support RDF Turtle Format

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#405]
`kgtk import-ntriples` could support RDF Turtle format.

For example, RDF Turtle format allows literal strings to be quoted in single quotes (`'`) as well as double quotes (`"`).

**Comment by szeke** [comment]
We should **not** add support for TTL as TTL is complex. People should run a TTL to triples converter before importing in KGTK

**Comment by szeke** [comment]
We should add to the documentation the magic graphy.io incantation that converts TTL to triples, it should be a variant of
```
$ curl http://dbpedia.org/data/Red_banana.ttl \
    |  graphy read -c ttl / tree / write -c ttl  > pretty.ttl
```

**Comment by CraigMiloRogers** [comment]
Documentation added.
