### ISSUE TITLE
kgtk validate and date values with YYYY-MM format

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#420]
**Is your feature request related to a problem? Please describe.**

I have a kgtk file with lines like these:

lattes:8164403687403639#83	lattes:8164403687403639#70	https://www.wikidata.org/wiki/Property:P580	**1994-02**	
lattes:8164403687403639#84	lattes:8164403687403639#70	https://www.wikidata.org/wiki/Property:P582	**1996-02**	
lattes:8164403687403639#933     lattes:8164403687403639#929     https://www.wikidata.org/wiki/Property:P580     **2013-08**

When I run kgtk validate, it reports the following erros and discards the lines

col 3 (node2) value '1996-02' is an Invalid Quantity
col 3 (node2) value '1994-02' is an Invalid Quantity

I used "--invalid-value-action REPORT" to avoid the discard

**Describe the solution you'd like**

Nodes about date properties (like https://www.wikidata.org/wiki/Property:P580 or https://www.wikidata.org/wiki/Property:P582) should not be considered invalid. 

**Describe alternatives you've considered**

Maybe another parameter to specify allowed date formats

**Additional context**

![image](https://user-images.githubusercontent.com/46487949/125213558-0065ca80-e289-11eb-8f29-1b88b43da936.png)

**Comment by szeke** [comment]
Hi, in KGTK dates have a special format as in `^1984-10-26T00:00:00Z/11`. Dates and times: temporal literals are started with a ^ caret character (indicating the tip of a clock hand) and followed by an ISO 8601 date and an optional precision designator, for example: ^1839-00-00T00:00:00Z/9

The documentation is in https://kgtk.readthedocs.io/en/latest/specification/:

**Comment by versant2612** [comment]
Thanks @szeke. I edited the input file to add '^' at the begining of date values.
