### ISSUE TITLE
Non-English data returned when `language=en` set in API call

### ISSUE THREAD

**Issue by aphedges** [usc-isi-i2/kgtk#421]
**Describe the bug**
When the `language=en` is set for an API call, non-English data will still be returned.

**To Reproduce**
1. Go to <https://kgtk.isi.edu/api?q=Q571&extra_info=true&language=en>
2. See the values for `alias` are in Polish (see [Q571](https://www.wikidata.org/wiki/Q571) (book))

For a second example:
1. Go to <https://kgtk.isi.edu/api?q=Q3947&extra_info=true&language=en>
2. See the values for `alias` are in Italian (see [Q3947](https://www.wikidata.org/wiki/Q3947) (house))

This appears to only be an issue for Qnodes that lack English aliases.

**Expected behavior**
Only English should be returned when `language=en`.

**Comment by saggu** [comment]
I have made the changes. Closing.

**Comment by aphedges** [comment]
Thanks for the quick fix!
