### ISSUE TITLE
Command instances does not exist

### ISSUE THREAD

**Issue by dfdazac** [usc-isi-i2/kgtk#452]
**Describe the bug**
I am using the docker image, and after importing a Wikidata dump, I wanted to try one of the examples in the README:

```sh
kgtk instances --transitive --class Q13442814,Q12345678
```

This results in the following error:

```sh
usage: kgtk [options] command [ / command]*
kgtk: error: argument command: invalid choice: 'instances' (choose from 'add-id', 'calc', 'cat', 'clean-data', 'compact', 'deduplicate', 'connected-components', 'expand', 'explode', 'denormalize_node2', 'export-gt', 'export-neo4j', 'export-wikidata', 'extract-wikidata-json', 'filter', 'generate-mediawiki-jsons', 'generate-wikidata-triples', 'graph-embeddings', 'graph-statistics', 'ifempty', 'ifexists', 'ifnotempty', 'ifnotexists', 'implode', 'import-atomic', 'import-concept-pairs', 'import-conceptnet', 'import-framenet', 'import-ntriples', 'import-visualgenome', 'import-wikidata', 'import-wordnet', 'join', 'lexicalize', 'lift', 'md', 'normalize', 'lower', 'normalize-edges', 'normalize-nodes', 'paths', 'query', 'reachable-nodes', 'remove-columns', 'rename-columns', 'reorder-columns', 'sort', 'sort2', 'split', 'tee', 'text-embedding', 'unique', 'unreify-rdf-statements', 'unreify-values', 'validate-properties', 'filter-properties', 'validate', 'zconcat')
```

**To Reproduce**
 Run

```sh
kgtk instances --transitive --class Q13442814,Q12345678
```

**Expected behavior**

I would expect KGTK to compute instances of the subclasses of the given classes.

**Desktop**
 - OS: Debian (from what I can see in the docker image)
 - Version of KGTK: 0.7.1

**Comment by CraigMiloRogers** [comment]
Our documentation is out of date.  We will create new sample commands in README.md and regenerate the docker file.

**Comment by filievski** [comment]
@dfdazac, I believe you hit the only command that we have stopped supporting over time 😄 
Luckily, many of the workflow can now be supported with the single command query​ (documentation), described in the paper I shared recently (also attaching it here). We call this "Kypher" internally, as it is a KGTK variant of Neo4j's Cypher.

Here is an example query (from a Jupyter Notebook) that queries the P279star file for instances of those two Qnode classes. This is the equivalent of what Daniel had in the issue. 

!filename="derived.P279star.tsv.gz"
!kgtk query -i $filename \
--match '()-[P279star]->(c)' \
--where 'c IN ["Q13442814", "Q12345678"]' \
--limit 10

Note that we fix the transitive requirement by precomputing a transitive closure over P279 and storing that in the P279star file.

The Wikidata files for the dump of 20210215, including the `derived.P279star.tsv.gz` file can be found here: https://drive.google.com/drive/u/1/folders/16afEfKJGJDVXwUhnTVrgdceQC7ddNOAC

@CraigMiloRogers please update the documentation to avoid future confusion, before closing this issue.

**Comment by CraigMiloRogers** [comment]
`install.md` has been updated in the `dev` branch.
