### ISSUE TITLE
reachable-nodes: the rootfilecolumn argument has no effect for node files

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#470]
Here is an example invocation that fails if the root file has `node1` as the header.
```
!$kgtk reachable-nodes \
    --rootfile $TEMP/human_settlement.tsv.gz \
    --rootfilecolumn node1 \
    --label "P131star" \
    --selflink \
    -i "$TEMP"/P131.tsv.gz
```

If I rename the header to `id` and supply `id` in `rootfilecolumn` the command works (`id` is the default for node files, so it may be that the argument is ignored)

**Comment by CraigMiloRogers** [comment]
Pedantically speaking, a file with a `node1` column and not an `id` column is not a node file.

**Comment by CraigMiloRogers** [comment]
Given file `root;tsv`:
```node1
aaa
bbb
ccc
```

and file `input.tsv`:
```node1   label   node2
aaa     P131star        aaa1
bbb     P131star        bbb1
```

The command:
```
