### ISSUE TITLE
Exception in clean_data while cleaning wikidata_qualifiers_20200504.tsv.gz

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#52]
The file `wikidata_qualifiers_20200504.tsv.gz` seems to have a large number of errors (reported by Itay), I tried to run `clean_data` on it and it threw an exception:

```
(kgtk-env) D22ML-PSZEKELY:wikidata-20200504 pedroszekely$ gzcat wikidata_qualifiers_20200504.tsv.gz | pv -p -s 24077191262 | kgtk clean_data --repair-month-or-day-zero 2> ~/Downloads/kgtk-err.txt | gzip > ~/data/wikidata-20200504/wikidata_qualifiers_20200504-clean.tsv.gz
 0.21% | 14570 ETA | 48.75MB Transferred | 1.57MB/sevents.js:186
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (/usr/local/lib/node_modules/pv/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Socket.emit (events.js:209:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:449:5)
    at onwrite (_stream_writable.js:470:5)
    at internal/streams/destroy.js:49:7
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:7:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:88:12) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by szeke** [comment]
The errors found by `clean_data` before it threw and exception

[kgtk-err.txt](https://github.com/usc-isi-i2/kgtk/files/4693032/kgtk-err.txt)

**Comment by CraigMiloRogers** [comment]
That error is being thrown by Javascript code.  I don't think KGTK has any Javascript code.

**Comment by CraigMiloRogers** [comment]
/usr/local/lib/node_modules/pv/

That's the vital clue.  There are mulitple implementations of `pv`. I'm using the C implementation. You're using the nodejs implementation.

**Comment by CraigMiloRogers** [comment]
Which version of nodejs pv do you have installed? A quick google reveals similar bugs in earlier versions.

**Comment by szeke** [comment]
Oh, so it is failing because of `pv`. Sigh. 

In any case, please validate the qualifiers file as Itay told me that it has many errors.

**Comment by CraigMiloRogers** [comment]
It may be just nodejs pv responding to the downstream part of the pipe exiting early due to exceeding the error limit.

**Comment by CraigMiloRogers** [comment]
Try adding `--error-limit 0` to the `clean_data` options.

**Comment by szeke** [comment]
@CraigMiloRogers please run the validator and cleaner on the qualifiers as I think it will uncover issues in the Wikidata import that we have to go fix, so sounds like a thorough analysis is needed on the Wikidata import.

I will close this issue as it there is this is not a bug in clean.
