### ISSUE TITLE
Update connected components command to understand node/edge file conventions

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#53]
The connected components command uses non standard options to specify columns to operate on:
```
--noheader: Option to specify that the input file does not contain a header.
--subj {integer}: Column in which the subject is given. Default: 0.
--pred {integer}: Column in which the predicate is given. Default: 1.
--obj {integer}: Column in which the object is given. Default: 2.
```

The task is to update the command to follow the same conventions as the others.

**Comment by szeke** [comment]
Assigning to @saggu so he becomes familiar with how to handle the options in KGTK commands.

**Comment by saggu** [comment]
Updated the command in `dev` branch
