### ISSUE TITLE
Error in remove_columns when removing multiple columns, separated by space

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#54]
I am using the following command to remove the exploded columns from a Wikidata file:
```
kgtk remove_columns -c 'id,rank,node2;magnitude,node2;unit,node2;date,node2;item,node2;lower,node2;upper,node2;latitude,node2;longitude,node2;precision,node2;calendar,node2;entity-type'
```
If I put spaces between the column names, eg, `id, rank, node2;magnitude` it doesn't work.

This command also has a non-standard `-dt` option.

**Comment by szeke** [comment]
Assigning to @CraigMiloRogers. We have a larger question that we should discuss, and it is whether we separate multiple arguments for an option with space, comma, and whether spaces can appear after the comma? How about TAB?

**Comment by CraigMiloRogers** [comment]
I prefer space as a separator in lists, mainly because I'm using Python's argparse and that's what it supports.  I could retool to support commas with optional whitespace, or both patterns (whitespace or commas with optional whitespace), although that will make argument parsing a little more complex.

**Comment by CraigMiloRogers** [comment]
I am somewhat opposed to using commas as a list separator because then we are effectively prohibiting them as characters in list items.

**Comment by szeke** [comment]
I don't care either way, but we need to standardize

**Comment by saggu** [comment]
As per consensus in yesterday's RP's meeting, we will use `space`
