### ISSUE TITLE
kgtk.exceptions.KGTKException: database or disk is full

### ISSUE THREAD

**Issue by valecarriero** [usc-isi-i2/kgtk#554]
**Describe the bug**
After some hours of running, a query returns  `kgtk.exceptions.KGTKException: database or disk is full`

**To Reproduce**
-  I run it on a server (RAM: 100 GB, hard disk: 2 TB)
- I used [these files](https://drive.google.com/file/d/18VGq56BTOHU7ui_WkfcfzL-0hNAIZB0T/view) linked in [this GitHub comment](https://github.com/usc-isi-i2/kgtk/issues/529#issuecomment-940896353)
- I installed KGTK with pip, with the following commands
```
conda create -n kgtk-env python=3.8
conda activate kgtk-env
conda install -c conda-forge graph-tool
pip --no-cache install -U kgtk
python -m spacy download en_core_web_sm
```
- I run this command: `kgtk --debug query --graph-cache wikidata.sqlite3.db -i edgefile_sorted.tsv --limit 10` and I obtained a `.db` file of 186 GB
- I run this: `export kypher="kgtk --debug query --graph-cache wikidata.sqlite3.db"`
- I tried this query with the aim to extract the subgraph of Wikidata related to composers compatible with subsequent queries on it:
```
$kypher -i edgefile_sorted.tsv -o composer_subgraph.tsv.gz --match '(o)<-[l {label: property}]-(s)-[:P106]->(:Q36834)' --return 'l as id, s as node1, property as label, o as node2'
```
- After running for many hours, I got `kgtk.exceptions.KGTKException: database or disk is full` and `composer_subgraph.tsv.gz` is empty

**Comment by valecarriero** [comment]
> From @chalypso: When the database imports and indexes files, it creates temporary files in a temp directory, so it can roll back things in case stuff goes wrong (they don't have names so you can't actually see them when you check a directory). Sometimes that temporary directory is in an area of your file system where you don't have enough room, particularly if you are importing lots and lots of data. You can use the environment variable SQLITE_TMPDIR to point somewhere where you have room, preferably the same directory where you are creating the graph cache. For example:
> 
> ```
> export SQLITE_TMPDIR=/data/tmp
> ```
> 
> We've run into this issue before with very large datasets and this solved it. Let us know if that does the trick. I should probably add a section on that to the manual. Also, you'll get much better query performance if the graph cache resides on an SSD, not a spinning hard disk.

Hi, I rerun everything specifying this variable, and after a few hours I now have the correct output tsv! Thanks!

**Comment by dgarijo** [comment]
Leaving the issue open until we add this into a FAQ document.

**Comment by chalypso** [comment]
I added a paragraph to the graph cache section of the manual on how to handle this issue.  I'll see if I can configure this automatically perhaps, but at least it is documented for now.
