### ISSUE TITLE
Reachable node inverted property bug

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/kgtk#557]
Running the reachable-nodes with inverted-prop returns too many rows.
```
$ kgtk reachable-nodes -i graph.tsv.gz --inverted-prop P749 --root QFS_entity065JNF-E | wc
18160   54480  871650
```
It should return only 273 rows.

The file graph.tsv.gz contains two type of edges. If there only P749 edges in the file, then the reachable-nodes returns the correct answer.

Contact @kyao for the graph.tsv.gz file.

**Comment by CraigMiloRogers** [comment]
@kyao You need to provide the list of properties: `--props P749`.  Otherwise, all properties are considered.

`--props` gives the list of properties to consider (or `--props-file`).  `--inverted-props` (or `--inverted-props-file`) says which of the properties under consideration are inverted.

**Comment by CraigMiloRogers** [comment]
I've documented the interaction between `--props` and `--inverted-props` in the .md file.
