### ISSUE TITLE
Clarify documentation of --output-stats in graph_statistics

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#56]
The documentation says:
```
--output-stats        do not output the graph but statistics only
```
It is unclear what this option means, should clarify.

I think we need the following options:
- ability to put the global statistics of the graph in a file
- ability to echo the original graph, adding the statistics edges at the end
- ability to only output the statistics edges

**Comment by filievski** [comment]
Addressed by https://github.com/usc-isi-i2/kgtk/commit/d6ccabcbaa724f640fb31c202a2e820d5ea79452

Updated documentation also on read-the-docs:
https://kgtk.readthedocs.io/en/latest/stats/
