### ISSUE TITLE
`--lang` option not working in `import-wikidata`

### ISSUE THREAD

**Issue by xu94-nlp** [usc-isi-i2/kgtk#564]
Hello all.

I'm trying to extract triples in WikiData by the following commands:

```bash
$ kgtk --debug --timing --progress import-wikidata \
          -i  latest-all.json \
          --node nodefile_en,jp.tsv \
          --edge edgefile_en,jp.tsv \
          --qual qualfile_en,jp.tsv \
          --use-shm True \
          --procs 20 \
          --mapper-batch-size 5 \
          --max-size-per-mapper-queue 5 \
          --single-mapper-queue True \
          --collect-results True \
          --collect-separately True \
          --collector-batch-size 15 \
          --collector-queque-per-proc-size 4 \
          --progress-interval 500000 --fail-if-missing False \
          --lang en,jp
```
During the processing nothing happened and it takes ~2.5 hours to finish, the output is:

```bash
Timing: elapsed=2:39:37.619911 CPU=0:37:15.875550 ( 23.3%): import-wikidata -i latest-all.json --node nodefile_en,jp.tsv --edge edgefile_en,jp.tsv --qual qualfile_en,jp.tsv --use-shm True --procs 20 --mapper-batch-size 5 --max-size-per-mapper-queue 5 --single-mapper-queue True --collect-results True --collect-seperately True -collector-batch-size 15 --collector-queue-per-proc-size 4 --progress-interval 500000 --fail-if-missing False --lang en,jp  
```
However, it seems that `--lang`` option is not working, as I had run the same command without `--lang` option (because I forgot to add it). 

**The outputed files (`edge*.tsv`, `node*.tsv`, `qual*.tsv`) with or without `--lang` option are with the same size**, since the default value used in `--lang` is `en`, I'm assuming `--lang en,jp` would produce a larger file but it's not the case. Is there anything I did wrong or is it a bug in current version?

Thank you very much for your reading.

**Comment by saggu** [comment]
Hi @xu94-nlp , I don't see the code `jp`. Are you trying to get Japanese labels? The code for that is `ja`.

https://www.wikidata.org/wiki/Help:Wikimedia_language_codes/lists/all

**Comment by saggu** [comment]
We created this notebook for importing wikidata on a laptop. Check it out as well, https://github.com/usc-isi-i2/kgtk/blob/dev/use-cases/import-wikidata.ipynb

**Comment by xu94-nlp** [comment]
> We created this notebook for importing wikidata on a laptop. Check it out as well, https://github.com/usc-isi-i2/kgtk/blob/dev/use-cases/import-wikidata.ipynb

Thank you very much for your help and rapid reply! This is exactly what I'm trying to make! Thanks!

**Comment by saggu** [comment]
Closing this issue.
