### ISSUE TITLE
Add documentation for low barrier import and export experiments

### ISSUE THREAD

**Issue by cknoll** [usc-isi-i2/kgtk#569]
I want to explore kgtk and its data format whether its potentially fits my use case.

To this end I do not want to import a whole wikidata dump (for performance and hd capacity reasons etc) but instead only a small subgraph.

It would be nice if there was a notebook which would show how to do this, i.e.
1. generating a subgraph from wikidata e.g. via a SPARQL query (say 1000 nodes),
2. importing this subgraph to kgtk
3. evaluate/manipulate it with kgtk and then
4. export it to an appropriate format
5. run a SPARQL query on that exported data

These steps would imho represent one intended use of kgtk as depicted by Fig. 1 on https://kgtk.readthedocs.io/en/latest/

Wrt. (5):
- It would be nice if this could be done without leaving the python world (e.g. use rdflib)
- I know kypher is much faster, but my current interest is more in the type of problems which can be solved with this tool chain then in performance.

**Comment by szeke** [comment]
Hi, thanks for your interest in KGTK. Please see the notebooks in the tutorials github. Two tutorials are relevant to your use case of importing data from SPARQL. One is importing data from CSV (you can write a SPARQL query and return the results in CSV): https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/04-kg-enrichment-with-csv.ipynb

The second tutorial is about importing ntriples: https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/05-kg-enrichment-with-lod.ipynb

**Comment by cknoll** [comment]
Thanks. I already saw these notebooks. However, they seem not to cover what I am looking for:
Some Notebook that I could run on my machine without any adaptation and which produces some nontrivial but easily comprehensible results with a runtime of < 2 min.

The first showstopper for this is the usage of several absolute user-specific paths like `kgtk_path = "/Users/pedroszekely/Documents/GitHub/kgtk"`. This implies that the notebook will probably not run out of the box and I have to figure out which files have to be downloaded and where to put them etc. Solveable problems, but imho undesirable friction.

The second hurdle is that imho the notebook is too long to digest. I am looking for a reasonably short self-contained getting-started-notebook.

Maybe I will try to create one myself as a learning project, but this is unsure.
