### ISSUE TITLE
generate_wikidata_triples ignores a valid ISO date if it does not start with `^`

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#58]
`2014-04-01T00:00:00Z/9` is a valid data in ISO format, but the command ignores it and throws an error because the string does not start with `^`.

This should be handled in the command

**Comment by szeke** [comment]
The KGTK file format specifies that dates must start with `^`. If you run the validator, I am guessing it will complain. In the near future it will be possible to put the ISO dates in the exploded columns, and the code will parse the exploded columns and create the correct structured literal.

For now, `node2` must comply with the spec.
