### ISSUE TITLE
kgtk paths without --path-file raised error

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#627]
**Describe the bug**
kgtk paths without --path-file raised error but --path-file if an optional parameter

**To Reproduce**

(kgtk-env) cloud-di@vmm-template:~/kgtk$ kgtk paths --max_hops 2 --path-mode NONE -i $FRIENDS -o $PATHS --statistics-only                                       
Missing node1 (source) column name in the path file.
Missing node1 (target) column name in the path file.
Exiting due to missing columns.

**Expected behavior**

kgtk paths without --path-file parameter should generate all paths from the input graph

**Comment by saggu** [comment]
Hi @versant2612 I think the documentation is being misinterpreted, `kgtk paths` does need an input file or `-` for stdin. The goal of this command is to find paths between a pair of nodes.

It is too expensive of a command, CPU resources wise, to be running on the whole graph. We will make the documentation clearer.

Hope this explanation helps.

**Comment by versant2612** [comment]
Thank @saggu for the explanation.
