### ISSUE TITLE
Numeric sorting

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#64]
**Describe the bug**
Sort does not allow for numeric sorting, it always performs string sorting.

**To Reproduce**
1. Jun tried to compute PageRank by using `graph_statistics`
2. then he used `kgtk sort` on the resulting PageRank statistics

**Expected behavior**
The sort should accept a flag `--numeric` that makes it perform a numeric rather than lexical sort.

**Desktop (please complete the following information):**
Jun's laptop (don't know the specs)

**Comment by chalypso** [comment]
sort already does allow numeric sorting through the -X flag which can pass the -n flag to the underlying sort.  See second example below.  I can promote that to a --numeric option.  One issue with that is that in a simple way it will apply to all sort columns, but as long as only one sort column is specified, it would be fine. 

`> cat /tmp/test.csv | kgtk sort -c 2
node	rank
otto	10
hans	2.0
franz	30
> cat /tmp/test.csv | kgtk sort -c 2 -X'-n'
node	rank
hans	2.0
otto	10
franz	30
`

**Comment by szeke** [comment]
Not a bug
