### ISSUE TITLE
"Waiting for the workers to shut down": it's been running for days and seems stuck

### ISSUE THREAD

**Issue by valecarriero** [usc-isi-i2/kgtk#648]
**Describe the bug**
after the message

```
Done processing /media/4TB/WikiData/wikidata-20220321-all.json.bz2
Telling the workers to shut down.
Waiting for the workers to shut down.
Exiting worker process 1 (pid 3875651).
Exiting worker process 0 (pid 3875650).
```

the process seems stuck and I don't have the expected output files, but only what they seem to be temporary files (maybe?)

**To Reproduce**
- wikidata dump I processed: https://dumps.wikimedia.org/wikidatawiki/entities/20220321/wikidata-20220321-all.json.bz2
- KGTK was installated with the following commands: 
```
conda create -n kgtk-env39 python=3.9
conda activate kgtk-env39
conda install -c conda-forge graph-tool
pip install etk==2.2.8
pip --no-cache install -U kgtk
python -m spacy download en_core_web_sm
```
- command I run for importing wikidata
```
kgtk --debug --timing --progress import-wikidata -i /media/4TB/WikiData/wikidata-20220321-all.json.bz2 --node wikidata-kgtk/nodefile.tsv --edge wikidata-kgtk/edgefile.tsv --qual wikidata-kgtk/qualfile.tsv --progress-interval 500000 --fail-if-missing False
```
- after processing wikidata for a few hours, I got this message, and it's still the same since Friday evening
```
Done processing /media/4TB/WikiData/wikidata-20220321-all.json.bz2
Telling the workers to shut down.
Waiting for the workers to shut down.
Exiting worker process 1 (pid 3875651).
Exiting worker process 0 (pid 3875650).
```
- in the output folder, this is what I have since Friday
```
-rw-rw-r-- 1 valentina valentina  91G apr  8 20:19 edgefile.tsv_0
-rw-rw-r-- 1 valentina valentina  91G apr  8 20:19 edgefile.tsv_1
-rw-rw-r-- 1 valentina valentina  203 apr  8 14:03 edgefile.tsv_header
-rw-rw-r-- 1 valentina valentina 4,6G apr  8 20:19 nodefile.tsv_0
-rw-rw-r-- 1 valentina valentina 4,6G apr  8 20:19 nodefile.tsv_1
-rw-rw-r-- 1 valentina valentina   41 apr  8 14:03 nodefile.tsv_header
-rw-rw-r-- 1 valentina valentina  30G apr  8 20:19 qualfile.tsv_0
-rw-rw-r-- 1 valentina valentina  30G apr  8 20:19 qualfile.tsv_1
-rw-rw-r-- 1 valentina valentina  193 apr  8 14:03 qualfile.tsv_header
```
is this an output I can use anyway? If so, how?

**Expected behavior**
The process stops, and I have the correct output files.

**Comment by valecarriero** [comment]
These are the first lines of the edgefile and nodefile outputs provided by kgtk

- edgefile.tsv_header
```
id	node1	label	node2	rank	node2;magnitude	node2;unit	node2;date	node2;item	node2;lower	node2;upper	node2;latitude	node2;longitude	node2;precision	node2;calendar	node2;entity-type	node2;wikidatatype	lang
```
- edgefile.tsv_1
```
Q42-P31-Q5-q42$f078e5b3-f9a8-480e-b7ac-d97778cbbef9-0	Q42	P31	Q5	normal				Q5						item	wikibase-item	
Q42-P21-Q6581097-q42$39f4de4f-c277-449c-9f99-512350971b5b-0	Q42	P21	Q6581097	normal				Q6581097				item	wikibase-item	
Q42-P106-Q214917-q42$e0f736bd-4711-c43b-9277-af1e9b2fb85f-0	Q42	P106	Q214917	normal				Q214917					item	wikibase-item
```
- edgefile.tsv_0
```
Q31-P2924-75f3f4c6-q31$e182ea43-a631-44af-94f9-a0fa8dfc3ac2-0	Q31	P2924	"4075290"	normal								external-id	
Q31-P1344-Q1088364-q31$7c0dca8a-cfae-4ed9-b5fd-69bb380ce331-0	Q31	P1344	Q1088364	normal				Q1088364				item	wikibase-item	
Q31-P1082-c8d96b49-q31$93ba9638-404b-66ac-2733-e6292666a326-0	Q31	P1082	+11150516	normal	+11150516						quantity	
```
- nodefile.tsv_header
```
id	label	type	description	alias	datatype
```
- nodefile.tsv_0
```
Q31	'Belgium'@en	item	'country in western Europe since 1830'@en	'Kingdom of Belgium'@en|'BEL'@en|'be'@en|'🇧🇪'@en|'BE'@en|'België'@en|'Koninkrijk België'@en|'Royaume de Belgique'@en|'Belgique'@en|'Königreich Belgien'@en|'Belgien'@en	
Q8	'happiness'@en	item	'mental or emotional state of well-being characterized by pleasant emotions'@en	'joy'@en|'happy'@en|'Happiness'@en	
Q23	'George Washington'@en	item	'1st president of the United States (1732−1799)'@en	'Washington'@en|'President Washington'@en|'G. Washington'@en|'Father of the United States'@en|'The American Fabius'@en	
```
- nodefile.tsv_1
```
Q42	'Douglas Adams'@en	item	'English writer and humorist (1952-2001)'@en	'Douglas Noel Adams'@en|'Douglas Noël Adams'@en|'Douglas N. Adams'@en	
Q1868	'Paul Otlet'@en	item	'Belgian author, librarian and colonial thinker'@en	'Paul Marie Ghislain Otlet'@en|'Paul Marie Otlet'@en	
Q2013	'Wikidata'@en	item	'free knowledge database hosted by Wikimedia and edited by volunteers'@en	'WD'@en|'WKP'@en|'d:'@en|'wikidata.org'@en|'m.wikidata.org'@en|'www.wikidata.org'@en
```

**Comment by dgarijo** [comment]
@valecarriero,
sorry, I meant in the console output. When the workers hang it's usually due to some weird encoding on the input files.

**Comment by saggu** [comment]
@valecarriero which version of KGTK are you using? you can find that by running `pip freeze | grep kgtk`

The installation instructions you mentioned look out of date.

Also, which OS are you running the import on?

**Comment by valecarriero** [comment]
> @valecarriero, sorry, I meant in the console output. When the workers hang it's usually due to some weird encoding on the input files.

These are kind of things it prints while processing, I thought they were normal:
```
*** Qualifier collision #1 detected for Q62481-P26-Q2086776-q62481$2f881f16-a9d0-4176-bebb-3b06995a1ab6-0-P580-360391cd (^1561-10-12T00:00:00Z/11)
```

```
*** Sitelink collision #1 detected for Q5882248-wikipedia_sitelink-1cc4bd87 (http://.wikipedia.org/wiki/Template:Documentation_subpage)
```

Also, I'm trying to process [another version of wikidata](https://dumps.wikimedia.org/wikidatawiki/entities/20220404/wikidata-20220404-all.json.gz) just now and I get the same messages

**Comment by saggu** [comment]
@valecarriero I am importing a new wikidata version using this notebook, https://github.com/usc-isi-i2/kgtk/blob/master/use-cases/import-wikidata.ipynb on a centos machine.

I'll keep you updated if I run into the same issue. Meanwhile give this notebook a try

**Comment by valecarriero** [comment]
> @valecarriero I am importing a new wikidata version using this notebook, https://github.com/usc-isi-i2/kgtk/blob/master/use-cases/import-wikidata.ipynb on a centos machine.
> 
> I'll keep you updated if I run into the same issue. Meanwhile give this notebook a try

Thank you very much @saggu, I run the first command of your notebook and I finally get the correct output from [this version ](https://dumps.wikimedia.org/wikidatawiki/entities/20220404/wikidata-20220404-all.json.gz)

However, it's not very clear to me what each step of the notebook does. 
For my purposes, I only need to query all the claims.
What exactly does the step _"Sort the files from TEMPDIR to DATADIR folder"_ do? 
I mean, do I need to run this, or not necessarily? 
If not, I would guess that just the `claims.raw.unsorted.tsv.gz` is enough for me, am I right?
Or do I need to run at least the _"Split somevalue and novalue from claims.raw.unsorted.tsv.gz"_ step and query just the `"somevalue"` file?
I'm a bit confused, sorry about that!

Also, I used to use the command `add-labels` on the output files of my queries, using a nodefile containing the labels. 
Can I use `add-labels` with `labels.en.unsorted.tsv.gz`?  I would say so based on the examples [here](https://kgtk.readthedocs.io/en/latest/transform/add_labels/), just want to be sure!
 
Sorry for the many questions!

Thanks again,
Valentina

**Comment by saggu** [comment]
@valecarriero You should run the whole notebook, the final version of the files in the `$DATADIR` are the ones you should use.

You can use the unsorted version, but I would run the notebook through.

Quick note: if you see this error `gsort command not found`, please change

```
os.environ['SORT_COMMAND'] = "sort"
```

**Comment by saggu** [comment]
Closing this issue. Please open it if there is still a pending concern
