### ISSUE TITLE
Graph visualization error 

### ISSUE THREAD

**Issue by sonfack** [usc-isi-i2/kgtk#652]
### **Describe the bug**
 **command:** kgtk visualize-graph -i hemg_edge.csv -o default.html
**Error on terminal:** invalid syntax (<unknown>, line 1)

### **To Reproduce**
kgtk visualize-graph -i hemg_edge.csv -o default.html

hemg_edge.csv
node1,label,node2
Cause_11,causes,Problem
Cause_12,causes,Problem
Cause_13,causes,Problem
H11,hasQuestion,Question_11
H12,hasQuestion,Question_11
H13,hasQuestion,Question_11
H11,hasDoubt,Doubt_11
H12,hasDoubt,Doubt_12
H13,hasDoubt,Doubt_13
H11,hasStatus,Status_11
H12,hasStatus,Status_12
H13,hasStatus,Status_13
H11,hasIteration,I1
H12,hasIteration,I1
H13,hasIteration,I1
I1,hasObservation,Observation_11
I1,hasObservation,Observation_12
H21,Cause_21,causes,Cause_13
H21,hasQuestion,Question_21
H21,hasDoubt,Doubt_21
H21,hasStatus,Status_21
H21,hasIteration,I2
H21,hasObservation,Observation_21
Problem,label,"KW831 rejection by customers"@en
Question_11,label,"Why were KW831 products rejected by customer ?"@en
Question_21,label,"Why could these recently manufactured KW831 poorly tight ?"@en
Observation_11,label,"Some operators were not trained on how to use measurement tools, so some could not measure KW831 components well"@en
Observation_12,label,"Measurement tools are new and where tested good Before usage, therefore are not faulty"@en
Doubt_11,label,"Almost certainly true"@en
Doubt_12,label,"Highly likely"@en
Doubt_13,label,"Highly likely"@en
Status_11,label,"Unknown"@en
Status_12,label,"Valid"@en
Status_13,label,"Valid"@en
Doubt_21,label,"Probably true"@en
Status_21,label,"Valid"@en
Cause_11,label,"Faulty measurement tools"@en
Cause_12,label,"non-compliance with the manufacturing plan"@en
Cause_13,label,"Over tightening"@en
Observation_21,label,"Only recently manufactured KW831 are rejected By customer"@en
Cause_21,"Work poorly done by operators"@en

### **Expected behavior**
Creation of a HTML page to visualize graph

**Comment by saggu** [comment]
Hi @sonfack ,

Thanks for submitting this bug. I have released a new version for kgtk==1.4.3 which has the fix for this bug.
Please try again with the latest kgtk version.

However the last line in your file is incorrect,
`Cause_21,"Work poorly done by operators"@en`

it should be 

`Cause_21,label,"Work poorly done by operators"@en`

Please find attached the html I generated
[default.html.zip](https://github.com/usc-isi-i2/kgtk/files/8872775/default.html.zip)

**Comment by szeke** [comment]
Please run `kgtk validate` as your syntax for language qualified strings is wrong, it should use single rather than double quotes. The parser is permissive in some commands, but best to be compliant with the syntax.
