### ISSUE TITLE
KGTK --where not matching

### ISSUE THREAD

**Issue by sonfack** [usc-isi-i2/kgtk#654]
**Describe the bug**
--where option not matching condition

**To Reproduce**
I do not understand why [--where] does not find any match condition

I want to reetrieve  all "Valid" iterations. My query is as follows:

kgtk query -i hemg_common_doubt.tsv  --match '(i)-[:hasHypothesis]->(h)-[:hasStatus]->(s), (n1)-[h]->(n2)' --where  'substr(s,1) = "Valid" '  --return 'i as `Iteration`, h as `Hypothesis`, s as `Status`,  n2 as `Consequence` '

No result.

Without [--where] I can find there are "Valid" status in the graph

kgtk paths  --path-file pairs.tsv  --path-mode NONE --path-source source --path-target target  -i  hemg_common_doubt.tsv

Outputs well 

**Graph**
id	node1	label	node2
H11	"Faulty measurement tools"	H11	"KW831s are rejected by customers"
H12	"Non-compliance with the manufacturing plan"	H12	"KW831s are rejected by customers"
H13	"Over tightening"	H13	"KW831s are rejected by customers"
e1	H11	hasQuestion	"Why were KW831 products rejected by customers?"
e2	H12	hasQuestion	"Why were KW831 products rejected by customers?"
e3	H13	hasQuestion	"Why were KW831 products rejected by customers?"
e3	H11	hasDoubt	"Almost certainly true"
e4	H12	hasDoubt	"Highly likely"
e5	H13	hasDoubt	"Highly likely"
e6	H11	hasStatus	"Unknown"
e7	H12	hasStatus	"Valid"
e8	H13	hasStatus	"Valid"
e9	I1	hasHypothesis	H11
e10	I1	hasHypothesis	H12
e10	I1	hasHypothesis	H13
e11	I1	hasObservation	"Some operators were not trained on how to use measurement tools so some could not measure KW831 components well"
e12	I1	hasObservation	"Measurement tools are new and where tested good Before usage therefore are not faulty"
H21	"Work poorly done by operators"	H21	"Over tightening"
e13	H21	hasQuestion	"Why were these recently manufactured KW831s poorly tight?"
e14	H21	hasDoubt	"Probably true"
e15	H21	hasStatus	"Valid"
e16	I2	hasHypothesis	H21
e17	I2	hasObservation	"Only recently manufactured KW831 are rejected By customer"
e18	I1	isBefore	I2
e19	I0	isBefore	I1
e20	I0	hasInitial	"KW831s are rejected by customers"
H31	"Measuring errors"	H31	"Non-compliance with the manufacturing plan"
H32	"Poorly trained operators on production chain"	H32	"Work poorly done by operators"
e21	I3	isAfter	I2
e22	H31	hasStatus	"Unknown"
e23	H31	hasQuestion	"Why were the dimensions of the KW831 parts not respected?"
e24	H32	hasStatus	"Valid"
e25	H32	hasQuestion	"Why are these newly recruited operators not good?"
e26	H31	hasDoubt	"Undecided"
e27	H32	hasDoubt	"Certainly true"
e28	I3	hasHypothesis	H31
e29	I3	hasHypothesis	H32
e30	I3	hasObservation	"There are newly recruited operators, so they can poorly mount or measure KW831 components"
e31	I3	hasObservation	"Operators worked under pressure in order to deliver KW831 products on time, so it is possible to have manufacturing errors"
e32	I3	hasObservation	"Newly recruited operators are inexperienced workers"

**Comment by saggu** [comment]
Hi @sonfack you dont have to use `substr` in your query `s="Valid"` should work. Anyway could you attach the tsv file to the issue.
Thanks

**Comment by sonfack** [comment]
It seems as if there is a problem with literal (strings)
To solve the problem, I changed the string nodes to symbolic nodes. 
The [--where] conditions become:
**--where 'substr(s,1,5) = kgtk_unstringify("Valid") '**
