### ISSUE TITLE
Have a single requirements file

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#73]
Right now there are 3 requirement files:

- requirements.txt, used for installation of kgtk.
- requirements-dev
- requirements-text_embeddings, which are now included in requirements.txt

Can we have just one? @saggu, @GreatYYX, @ckxz105 ?

**Comment by GreatYYX** [comment]
`setup.py` only includes `requirements.txt`. `requirements-dev.txt` is for development only (manual install with docs, test suites and so on). `requirement-text_embeddings ` could be either integrated or renamed to `requirements-full.txt` and automatically installed for full version.

**Comment by dgarijo** [comment]
Actually `requirement-text_embeddings.txt` is redundant, because all deps are already in `requirements.txt`

**Comment by GreatYYX** [comment]
> Actually `requirement-text_embeddings.txt` is redundant, because all deps are already in `requirements.txt` (I verified manually)

Right. Typically, it can be removed.
But I personally think it's not a proper design. If text-embedding is not a required module, we should remove it from lite installation and prune the size of the package.
So basically, it would have:
- requirement.txt for standard / full version (automatic packaged)
- requirement-lite.txt for lite version (automatic packaged)
- requirement-dev.txt for developer only

**Comment by dgarijo** [comment]
Correct, right now there is no "lite" installation. The docker image is 5.89 GB, which I would say is not pretty "lite" :)
BUT if we have a "lite" installation in the future, maybe it should not have the commands that require a complete install. Otherwise it's very confusing. Maybe we should wait until the whole kgtk stabilizes (v1.0.0) and have a branch for lite

**Comment by GreatYYX** [comment]
> Correct, right now there is no "lite" installation. The docker image is 5.89 GB, which I would say is not pretty "lite" :)
> BUT if we have a "lite" installation in the future, maybe it should not have the commands that require a complete install. Otherwise it's very confusing. Maybe we should wait until the whole kgtk stabilizes (v1.0.0) and have a branch for lite

Agree, this needs more comprehensive consideration.

BTW, we do have a "lite" version, but not documented since it was a temporary request from @saggu https://github.com/usc-isi-i2/kgtk/tree/feature/lite, it could run as `python setup.py install --lite`.

**Comment by ckxz105** [comment]
Remove the extra text embedding requirement file
