### ISSUE TITLE
Examples should be updated

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#82]
The kgtk code has changed so rapidly in the last 3 weeks that some of the commands used in the notebooks are no longer valid.

The notebooks should be updated accordingly.

**Comment by dgarijo** [comment]
In @filievski's notebook, I updated the data so the notebook will work. However, I did not update the description in the notebook itself.

**Comment by filievski** [comment]
Description updated:
https://github.com/usc-isi-i2/kgtk/commit/76d517d888b12726e2de9ec8be9300bf5beb1013

**Comment by dgarijo** [comment]
@filievski thanks, now we just need to make sure the other notebooks are updated too.

**Comment by filievski** [comment]
I have updated them with the text_embedding and graph_statistics' logging attribute already.
Are there any known issues?

**Comment by dgarijo** [comment]
I tried the notebook https://github.com/usc-isi-i2/kgtk/blob/dev/examples/Example5%20-%20AIDA%20AIF.ipynb and experienced some errors because the commands have changed.

**Comment by filievski** [comment]
Fixed on dev
