### ISSUE TITLE
Add_id's documentation of id-styles needs to be updated/clarified

### ISSUE THREAD

**Issue by filievski** [usc-isi-i2/kgtk#84]
The documentation of id-style options in https://kgtk.readthedocs.io/en/dev/transform/add_id/ seems confusing and needs to be updated/clarified. Namely, the first table conveniently lists the possible styles but the actual options in the command below are different (or at least, do not correspond 1-on-1 to the styles in the table).

**Comment by CraigMiloRogers** [comment]
The documentation should be updated now.
