### ISSUE TITLE
Update instructions: How to update KGTK?

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#85]
We have no instructions stating how to update an already installed version of KGTK.
In theory it should be as easy as:

```
git clone https://github.com/usc-isi-i2/kgtk/ 
cd /kgtk 
python setup.py install 
```

**Comment by GreatYYX** [comment]
- If it's from pip, then `pip install -U kgtk`.
- If it's from github, then `git pull && pip install .` or `git pull && python setup.py install`. If it was original installed as development, namely `pip install -e .`, then only need to do `git pull`.

**Comment by dgarijo** [comment]
Fixed in dev.
