### ISSUE TITLE
Import n-triples in help does not use ntriples format

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/kgtk#86]
In the KGTK help, import_ntriples is as follows: 

`gtk import_ntriples -i dbpedia_wikipedia_links.ttl -o DbpediaWikipediaLinks.tsv`

However, can the command use turtle file? Shouldn't the command be `.nt`?

**Comment by dgarijo** [comment]
I am assigning @rongpenl because he has the one in charge of the command (I believe). Please clarify! Thanks.

**Comment by dgarijo** [comment]
Also, @rongpenl  is the latest dev version still using underscores? I tried to use it, but I only got it working with `_`

**Comment by rongpenl** [comment]
@dgarijo Naren wrote this command before but since it can be treated as the inverse of my command so I can take a look. 

I think you are right. The extension should be `.nt` rather than `.ttl`. Naren's `import_ntriples` doesn't work on turtle file.

**Comment by rongpenl** [comment]
@dgarijo What do you mean using underscores? Which functionality are you using? Can you provide an example?

**Comment by dgarijo** [comment]
@rongpenl, latest version uses underscores: https://kgtk.readthedocs.io/en/latest/import/import_ntriples/ 

dev version uses hyphens: https://kgtk.readthedocs.io/en/dev/import/import_ntriples/

However, in my latest Docker build from the `dev` branch, `import-ntriples` is not recognized. I had to use the old one instead (import_ntriples).

**Comment by rongpenl** [comment]
I think it is because import-ntriples is only discussed/documented but not implemented yet. @CraigMiloRogers may know more about the latest status.

**Comment by dgarijo** [comment]
Let's discuss offline and address the issue, it doesn't look complicated.

**Comment by dgarijo** [comment]
This was a caching issue in the docker image
